### ISSUE TITLE
Jenkins setup

### ISSUE THREAD

**Issue by rvagg** [nodejs/citgm#10]
I've set up a Jenkins job to start playing around with this: <https://jenkins-iojs.nodesource.com/job/smoker>, currently only hooked up to a fast Linux slave while I test this out.

Successful run here: https://jenkins-iojs.nodesource.com/job/smoker/6/nodes=debian8-64/console (well, "successful" in the "it runs" sense, I'm only running 3 modules and hapi is failing 4 tests).

Jenkins config has the following for Linux after cloning the repo you give it (default nodejs/node) at the commit provided:

First compile and install Node:

```
./configure --prefix=$(pwd)/smoker
make -j $(getconf _NPROCESSORS_ONLN)
make install
```

then set up citgm:

```
export PATH=$(pwd)/smoker/bin:$PATH
cd smoker
node -v
npm -v
npm install --prefix=$(pwd) --global --loglevel=error citgm
```

then tests

```
export PATH=$(pwd)/smoker/bin:$PATH
export npm_config_nodedir=$(pwd)

cd smoker

citgm --nodedir=$npm_config_nodedir --lookup --verbose through2@latest
citgm --nodedir=$npm_config_nodedir --lookup --verbose bignum@latest
citgm --nodedir=$npm_config_nodedir --lookup --verbose hapi@latest
```

Some notes:

1. Can't run without `--verbose`, is this intended? Should we have a less verbose option?
2. `--nodedir` doesn't pass down properly if the module isn't set up quite right, e.g. https://github.com/justmoon/node-bignum/blob/5f668a1c44324fd2ec074bafb1bd215883d8e856/package.json#L37 (although I can fix that one by removing that line, but it's a useful case), hence the use of `export npm_config_nodedir=$(pwd)` to achieve the same thing.
3. I noticed when I some combination of commandline options wrong and it borked that it exited with code 0 indicating a pass, it's probably worth figuring out that path in bin/citgm (it's not immediately apparent to me just glancing through it).

Is this roughly how you envisioned it being used @jasnell, perhaps you can give some feedback?

**Comment by rvagg** [comment]
Also:

4. I'd like to get rid of the npm WARNings because of working against a `-pre` version of Node, `--loglevel=error` would be good all the way down, do we need to `export npm_config_loglevel=error` this too?

**Comment by rvagg** [comment]
Now running with this script:

```sh
export PATH=$(pwd)/smoker/bin:$PATH
export npm_config_nodedir=$(pwd)
export npm_loglevel=error
retval=0

cd smoker

citgm --nodedir=$npm_config_nodedir --lookup --verbose lodash@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose underscore@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose request@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose commander@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose express@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose chalk@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose q@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose colors@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose coffee-script@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose through2@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose bluebird@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose moment@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose yeoman-generator@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose glob@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose gulp-util@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose jade@latest || retval=1
# citgm --nodedir=$npm_config_nodedir --lookup --verbose redis@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose socket.io@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose fs-extra@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose body-parser@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose uglify-js@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose handlebars@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose rimraf@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose yosay@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose mime@latest || retval=1
# citgm --nodedir=$npm_config_nodedir --lookup --verbose mongodb@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose graceful-fs@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose bignum@latest || retval=1
citgm --nodedir=$npm_config_nodedir --lookup --verbose hapi@latest || retval=1

exit $retval
```

Example output:

https://jenkins-iojs.nodesource.com/job/smoker/8/nodes=debian8-64/console

Notes:

1. Setting the loglevel env var doesn't help, we're still getting WARN messages, need to be able to pass `--loglevel` all the way down because it's being overridden somewhere I think.
2. Way too noisy, it's impossible to sift through this output quickly enough to make this practical, we'll need to figure out a way of filtering. One thought is that we could setup a config file that runs these all instead of invoking them one by one and then spit out the results in TAP format to a `.tap` file and get Jenkins to pick that up and we'd have a simple version showing what's passed and what's failed.

There are a few interesting failures in there, e.g. express is fine except for the http status code names we changed:

```
      Uncaught AssertionError: expected '<p>Found. Redirecting to <a href="http://google.com">http://google.com</a></p>' to be '<p>Moved Temporarily. Redirecting to <a href="http://google.com">http://google.com</a></p>'
```

ws needs to be upgraded to nan@2, that shouldn't be hard to do, then socket.io should be closer.

**Comment by jasnell** [comment]
Awesome to see this being exercised... few things...

>Can't run without --verbose, is this intended? Should we have a less verbose option?

I tried really hard not to make any assumptions about how this should be used. I wrote it with the intent that we would tweak how it works based on what lessons we'd learn by using it. In terms of the `--verbose` output, what would be the most useful?

>--nodedir doesn't pass down properly if the module isn't set up quite right, e.g. >https://github.com/justmoon/node-bignum/blob/5f668a1c44324fd2ec074bafb1bd215883d8e856/package.json#L37 (although I can fix that 
> one by removing that line, but it's a useful case), hence the use of export npm_config_nodedir=$(pwd) 
> to achieve the same thing. 

Hmm... any suggestions then? Perhaps automatically set `npm_config_nodedir` when `--nodedir` is set?

> I noticed when I some combination of commandline options wrong and it 
> borked that it exited with code 0 indicating a pass, it's probably worth figuring out that path in bin/citgm 
> (it's not immediately apparent to me just glancing through it).

Yes, I'm actually not very happy with how complex the command line options are getting. Going to have to rethink that part of the interface.

> I'd like to get rid of the npm WARNings because of working against a -pre version of Node, 
> `--loglevel=error` would be good all the way down, do we need to export `npm_config_loglevel=error` this too?

Agreed. It's quite noisy.

One other approach I was considering was to set up a separate host that will run these continually, piping the install and test output to separate files. We could then just browse and see the output. Could be Jenkins integrated but that wouldn't really be a necessity.

**Comment by jasnell** [comment]
Ok, so I've added optional values to the `--verbose` switch now. Default is `info`, which is the most noisy. You can also do `warn` and `error`. The `npm` output is still limited to `error` regardless of this setting. Should we tie that in to the `--verbose` switch also? 

Next I will be looking at adding switches to redirect the output of the `npm install` and `npm test` phases to separate files.

**Comment by TheAlphaNerd** [comment]
I would definitely like to play more with getting this running in CI. Will be exploring this more in the near future

**Comment by TheAlphaNerd** [comment]
closing in lieu of #10 which has more discussion

**Comment by TheAlphaNerd** [comment]
Actually I lied. I'm leaving this one open and closing #10

**Comment by TheAlphaNerd** [comment]
Yay... it is running in CI and being used for releases ✨✨✨✨
