### ISSUE TITLE
Is the testing module always downloaded from npm?

### ISSUE THREAD

**Issue by simone-sanfratello** [nodejs/citgm#1009]
I'm trying to make fastify works on citgm; following urls are valid for citgm, but looks like the content is downloaded from npm instead from the repository location

```
git@github.com:simone-sanfratello/fastify.git#fix/citgm
git+https://github.com/simone-sanfratello/fastify#fix/citgm
github:simone-sanfratello/fastify#fix/citgm
simone-sanfratello/fastify#34814fd
```

Also, following urls format are not valid or are not working

```
http://github.com/jasnell/activitystrea.ms/archive/HEAD.tar.gz
https://github.com/npm/cli.git             > failure | incorrect header check)
```

**Comment by richardlau** [comment]
Yes, unless `useGitClone` is set:
https://github.com/nodejs/citgm/blob/c47ab1073bf21f1ff5b89987519197bd32c7e022/README.md?plain=1#L141

**Comment by simone-sanfratello** [comment]
Thanks

**Comment by SimenB** [comment]
`head: true` also works, I think?

https://github.com/nodejs/citgm/blob/c47ab1073bf21f1ff5b89987519197bd32c7e022/README.md?plain=1#L128

**Comment by richardlau** [comment]
> `head: true` also works, I think?
> 
> https://github.com/nodejs/citgm/blob/c47ab1073bf21f1ff5b89987519197bd32c7e022/README.md?plain=1#L128

Possibly. If someone wants to look through the logic, it's in `lookup()` in `lib/lookup.js`: https://github.com/nodejs/citgm/blob/b8193a7840adc340c6c77d211919d86722dce326/lib/lookup.js#L86-L209
