### ISSUE TITLE
jose@v4.15.2 not working on Node v21.x

### ISSUE THREAD

**Issue by alfonsograziano** [nodejs/citgm#1011]
Hi @panva I noticed you're listed as maintainer for jose so I'd like to bring to your attention that jose@v4.15.2 tests have been failing across different systems on v21.x. Feel free to loop in more contributors that you think may help.

Here a failed run for reference:
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3318/testReport/

As you can see on this run jose is failing on five different nodes. Can you please help us to debug the issue? I'm not sure if this is related to the new Node version or something inside the package.

**Comment by panva** [comment]
Hi, i'll take a look. This is unexpected since there are no crypto changes in v21

**Comment by panva** [comment]
What changed wrt zlib's inflateRaw/deflateRaw?

**Comment by alfonsograziano** [comment]
Not sure, maybe this can be related? https://github.com/nodejs/node/pull/50085/files
I see that has been merged yesterday and also the jose issue started yesterday

**Comment by panva** [comment]
Installing v21.0.0-nightly20231009387e2929fe on my local macOS system does not reproduce this issue. I suspect them to be platform related and they seem to be related to `inflateRaw`, and `deflateRaw` outputs from the `node:zlib` module.

The issue is that the test vector is deterministic and therefore expects a specific output, which on these runs was not provided.

**Comment by panva** [comment]
Yes, that's absolutely related.

**Comment by panva** [comment]
I'm compiling from main now.

**Comment by alfonsograziano** [comment]
Do you have any idea to fix the issue? Unfortunately my knowledge for now is not enough to figure out a proper solution by myself

**Comment by panva** [comment]
I'll compile from main to see if it's platform dependent or not, then we ask for the zlib update to be reverted.

**Comment by alfonsograziano** [comment]
Awesome, thanks!

**Comment by panva** [comment]
Opened nodejs/node#50138

**Comment by panva** [comment]
I will mark the test as non-deterministic and release a patch release to unblock citgm.

**Comment by alfonsograziano** [comment]
Awesome, thanks a lot!
