### ISSUE TITLE
replace readable-stream with stream in userland stream CI

### ISSUE THREAD

**Issue by mafintosh** [nodejs/citgm#103]
As discussed here, https://github.com/nodejs/node/pull/5251 when running the Streams CI that tests userland stream modules against node master we should consider replacing `require('readable-stream')` with `require('stream')` to actually test the stream impl in node master.

**Comment by TheAlphaNerd** [comment]
I'm imagining there are a few ways this could be done, although I'm not sure which would be the fastest. It would likely make the most sense to process the code after the tarball has been extracted, but before npm install is run

* text based regular expression replacement
  - could be done with sed
  - could be done with fs.readStream -> filter -> fs.writeStream
* AST based substitution
  - could be done with esprima
  - could be done with another AST tool

**Comment by TheAlphaNerd** [comment]
I think there is a way to do this now

/cc @nodejs/streams

**Comment by jasnell** [comment]
hmm... not sure about this one. I get the reasoning and don't necessarily disagree, but the whole point of citgm is to run the modules own tests exactly as they have been written. Perhaps this could be done with an optional flag?

**Comment by TheAlphaNerd** [comment]
My thoughts exactly... Add a flag and make it an option for the ci job

**Comment by calvinmetcalf** [comment]
the flag is READABLE_STREAM='disable'

**Comment by mcollina** [comment]
the problem we are trying to solve here are regressions in any change we land in streams in core. Given that most modules depends on `readable-stream`, it is hard to check if we introduce regressions. Running the CITGM with this flag set should be probably part of the release pipeline (if there are streams change).

**Comment by MylesBorins** [comment]
@gdams is this something you would want to tackle?

essentially we just need a new argument to set READABLE_STREAM='disable'

**Comment by gdams** [comment]
yup i'll take a look

**Comment by MylesBorins** [comment]
This is in CI now
