### ISSUE TITLE
`jest` flaky tests

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/citgm#1032]
`jest` has been a little flaky recently. The output errors are not that clear, so I decided to open this issue to gather more information

Reference: https://ci.nodejs.org/job/citgm-smoker/3350/nodes=fedora-last-latest-x64/testReport/junit/(root)/citgm/jest_v29_7_0/

Tested on v21.3.0-proposal.

ping @cpojer, @SimenB, @thymikee, and @jeysal

**Comment by SimenB** [comment]
We really should strip out the ansi codes somehow 😅 

Is the flake only for 21.3, or does it also happen for v18 and v20?

**Comment by targos** [comment]
It seems specific to v21 (citgm runs for v18 and v20 didn't show jest failures other than one timeout)
