### ISSUE TITLE
CITGM failures in node 22

### ISSUE THREAD

**Issue by rluvaton** [nodejs/citgm#1057]
It seems like
- yarn - https://github.com/yarnpkg/berry/issues/6267
- gulp - https://github.com/gulpjs/gulp/issues/2801
- import-in-the-middle: https://github.com/DataDog/import-in-the-middle/issues/73

fail the citgm on the latest version of node

opened this issue to track those sub issues

**Comment by RafaelGSS** [comment]
Closing in favour of #1060
