### ISSUE TITLE
CITGM is in deep trouble

### ISSUE THREAD

**Issue by targos** [nodejs/citgm#1067]
We got a regression in the latest v22.5.0 that affects at least yarn and npm: https://github.com/nodejs/node/issues/53902

It seems that citgm would have caught it, but for jobs end up green even when they have lots of failures.

From https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3457/nodes=debian12-x64/

```
22:06:57 warn: @nearform/bubbleprof npm-install:| npm error Exit handler never called!
22:06:57 warn: @nearform/bubbleprof npm-install:| npm error This is an error with npm itself. Please report this error at:                                                                                                
22:06:57 warn:                                  | npm error   <https://github.com/npm/cli/issues>                                                                                                                         
22:06:57 warn:                                  | npm error A complete log of this run can be found in: /home/iojs/tmp/citgm_tmp/bf0d267e-49e6-467a-bf5b-dcf938d40bcc/home/.npm/_logs/2024-07-16T20_05_57_634Z-debug-0.log
22:06:58 error: failure             | The canary is dead: 
22:07:03 error: @nearform/bubbleprof done| done - the test suite for @nearform/bubbleprof version 7.0.1 failed
22:07:03 (node:783693) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.
22:07:03 (node:783693) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.
22:08:09 warn: @nearform/doctor npm-install:| npm error Exit handler never called!
22:08:09 warn: @nearform/doctor npm-install:| npm error This is an error with npm itself. Please report this error at:                                                                                                
22:08:09 warn:                              | npm error   <https://github.com/npm/cli/issues>                                                                                                                         
22:08:09 warn:                              | npm error A complete log of this run can be found in: /home/iojs/tmp/citgm_tmp/50a9288d-b4f4-4ba6-88c9-df6e8ba9bca3/home/.npm/_logs/2024-07-16T20_07_07_903Z-debug-0.log
22:08:10 error: failure             | The canary is dead: 
22:08:16 error: @nearform/doctor done| done - the test suite for @nearform/doctor version 8.1.0 failed
```

**Comment by ljharb** [comment]
This is also filed as https://github.com/npm/cli/issues/7657, and https://github.com/nodejs/node/pull/53462 was pointed to me as a possible cause.

**Comment by targos** [comment]
I think the cause is https://github.com/nodejs/node/pull/53627, but this issue is not about the regression itself. It's about the fact that CITGM somehow reported successful runs instead of failures.

**Comment by targos** [comment]
@nodejs/build-infra I believe this is an issue with the Jenkins job. If I run `node bin/citgm-all.js --includeTags binary-split`, I can reproduce the regression and it correctly exits with code 1.

**Comment by richardlau** [comment]
Possibilities:
- The job runs citgm via `eval`:
```
# Using eval so we can use a complicated CITGM_COMMAND such as 'NODE_OPTIONS=--xzy citgm-all'
eval $CITGM_COMMAND "--nodedir=$npm_config_nodedir -v $CITGM_LOGLEVEL -x $PWD/report.xml -q $NPM_LOGLEVEL --tmpDir $temp"
```
- We have `Do not fail the build on empty test results` turned on
![image](https://github.com/user-attachments/assets/fdde34a1-d371-471e-88ea-347d7da6feef)

I'll turn off `Do not fail the build on empty test results`.

**Comment by richardlau** [comment]
Rerunning https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3457/nodes=debian12-x64/ with `Do not fail the build on empty test results` disabled:
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3459/nodes=debian12-x64/console

**Comment by richardlau** [comment]
> Rerunning https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3457/nodes=debian12-x64/ with `Do not fail the build on empty test results` disabled: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3459/nodes=debian12-x64/console

With `Do not fail the build on empty test results` disabled, the CITGM run for 22.5.0 now fails due to having no test results.

**Comment by richardlau** [comment]
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3459/nodes=debian12-x64/console

```
13:55:12 Recording test results
13:55:12 ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
```
which likely means `smoker/report.xml` wasn't generated:
![image](https://github.com/user-attachments/assets/2207d18e-0499-4413-98da-5ab702f62a5e)

we use  `-x` to specify outputting to `report.xml`.
```
# Using eval so we can use a complicated CITGM_COMMAND such as 'NODE_OPTIONS=--xzy citgm-all'
eval $CITGM_COMMAND "--nodedir=$npm_config_nodedir -v $CITGM_LOGLEVEL -x $PWD/report.xml -q $NPM_LOGLEVEL --tmpDir $temp"

```
```

**Comment by targos** [comment]
Here's the `report.xml` I get with Node.js 22.5.0 using the following command: `node bin/citgm-all.js --includeTags binary-split -x $PWD/report.xml`

[report.xml.zip](https://github.com/user-attachments/files/16319636/report.xml.zip)

**Comment by RedYetiDev** [comment]
FWIW another thing made it through CITGM: https://github.com/nodejs/node/issues/54518
