### ISSUE TITLE
Can citgm provide more options to ignore things?

### ISSUE THREAD

**Issue by smartmouse** [nodejs/citgm#11]
Some node-modules only support 64 bit node.js and not 32 bit node.js
Some do not support certain platforms, is there a way to skip running tests based on different conditions?
 arch, os, platforms,.. node.js bits.?

**Comment by jasnell** [comment]
The tool just runs `npm test` by default. There are two approaches you could take:

1. Use a custom test script instead; or
2. Have the npm test key off certain environment variables that can be set when launching citgm

**Comment by smartmouse** [comment]
Thanks for reply
