### ISSUE TITLE
Let's run citgm on all the things!

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/citgm#120]
v0.10: https://ci.nodejs.org/job/thealphanerd-smoker/193/
v0.12: https://ci.nodejs.org/job/thealphanerd-smoker/192/
v4: https://ci.nodejs.org/job/thealphanerd-smoker/191/
v5: https://ci.nodejs.org/job/thealphanerd-smoker/190/
master: https://ci.nodejs.org/job/thealphanerd-smoker/189/

**Comment by TheAlphaNerd** [comment]
Looking pretty good! I should really track down the flakiness of tape though

**Comment by jasnell** [comment]
+1
