### ISSUE TITLE
List of modules broken by node v6 to consider adding to smokesting

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/citgm#124]
* fsevents
* nsp
* babel-cli
* nodemon
* nan (if it can be testing in citgm

**Comment by TheAlphaNerd** [comment]
tracking use of deprecated apis https://github.com/strongloop/fsevents/issues/127

**Comment by reybango** [comment]
node-inspector

**Comment by jhnns** [comment]
[less](https://github.com/less/less.js)?

**Comment by mgol** [comment]
node-sass passes all tests on Node 6 but prints big stack traces to the console.

**Comment by TheAlphaNerd** [comment]
@mgol that is likely an underlying problem with nan + fsevents that is being fixed as we speak :dancer:

**Comment by fnando** [comment]
[pg](https://www.npmjs.com/package/pg)

**Comment by kirbysayshi** [comment]
[node-hid](https://github.com/node-hid/node-hid) appears broken and prints large stack traces as well.

**Comment by timurtu** [comment]
@mgol @TheAlphaNerd I noticed too with node-sass
