### ISSUE TITLE
Add modules that people use for testing

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#127]
- mocha
- chai
- sinon
- rewire
- mock-fs
- tap
- tape
- jest

Suggestions?

**Comment by ungoldman** [comment]
[standard](https://github.com/feross/standard) && [tape](https://github.com/substack/tape)

**Comment by krainboltgreene** [comment]
nightmare.js is great for acceptance tests!

**Comment by krainboltgreene** [comment]
chakram is a mocha helper set for HTTP API testing.

**Comment by wyze** [comment]
AVA

**Comment by matteofigus** [comment]
Karma and cheerio

**Comment by fiveisprime** [comment]
[Lab](https://www.npmjs.com/package/lab)

**Comment by stevelacy** [comment]
code / lab

**Comment by kulkarniankita** [comment]
Mocha and chai

**Comment by Trott** [comment]
nock

**Comment by ChiperSoft** [comment]
- Tape + selenium-webdriver + a bunch of custom tooling.
- Nightwatch

**Comment by MisterFantastic** [comment]
ReactStory book and Jest

**Comment by southpolesteve** [comment]
https://github.com/testdouble/testdouble.js

**Comment by bengl** [comment]
[mockery](https://github.com/mfncooper/mockery)

**Comment by TheAlphaNerd** [comment]
@GeorgeAdams95 do you want to run with putting together a PR for this?

**Comment by GeorgeAdams95** [comment]
sure!
