### ISSUE TITLE
npm is putting lots of garbage in $TEMPDIR

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/citgm#128]
I'm still chasing down where it is coming form. 

Right now I have found that every instance of `npm pack` is leaving folders in tempdir. If `npm pack`. Generally no assets are left in the tempdir, but if `npm pack` is called on a git repo the assets are left in the TMPDIR.

Since the temporary npm folder has a timestamp, this is resulting in our temp directories in CI growing with each run... 😅

We have a few potential solutions. citgm CI could manage TMPDIR... doing so could allow us to clean it with subsequent runs.

We could also introduce something like [tmpwatch](http://linux.die.net/man/8/tmpwatch) (thanks @othiym23) to do periodic cleaning of the temp directory.

@nodejs/npm @nodejs/build

**Comment by rmg** [comment]
For StrongLoop's CI I manage `TMPDIR` by creating a new directory with `mktemp` or similar and then setting `TMPDIR`, `npm_config_cache`, and `npm_config_tmp` to paths under it. Then I nuke the entire build's tmpdir at the end of the run.

Newer npm 3 is better at dealing with it, but with npm 1 I ran in to all sorts of problems when builds didn't get their own caches and tmpdirs.

**Comment by Fishrock123** [comment]
> For StrongLoop's CI I manage `TMPDIR` by creating a new directory with `mktemp` or similar and then setting `TMPDIR`, `npm_config_cache`, and `npm_config_tmp` to paths under it. Then I nuke the entire build's tmpdir at the end of the run.

Yeah, this is also what we do for `make test-npm` in core.
