### ISSUE TITLE
`npm smoketest`

### ISSUE THREAD

**Issue by jasnell** [nodejs/citgm#13]
I'm considering the possibility of adding a support for a `npm smoketest` convention. Essentially, if module developers want to include a `smoketest` script in their package.json as an alternative to `npm test`, then `citgm` would choose to run that as an alternative. Doing so would allow module developers to create subsets of the tests that make the most sense for smoke testing, or perform additional set up that may be necessary independently of the normal test suite.

**Comment by smartmouse** [comment]
That sounds like a good idea, do you have guidelines of what should go into smoketest?

**Comment by jasnell** [comment]
@smartmouse ... not so much yet. At the very least, some kind of consistent output for the tests themselves would be ideal. A package published to npm could include a minimal smoketest script that can help citgm bootstrap things so that the package doesn't have to publish it's tests to npm and we don't have to go hunting around github for the right version, etc. We'd have to work out exactly what that process would be tho

**Comment by mhdawson** [comment]
Consistent output would be key.   Having it separate sounds like a good way to know when we expect the output to be such that citgm can parse it and also to know when a module has "opted" in and we can provide more details on the results.  It might be nice to have a way for us to provide the smoketest  file outside of the module itself in cases were we wanted to build up tests on our own.  For example you might have a script which runs the standard tests and then post-processes the output into the form needed for citgm

**Comment by TheAlphaNerd** [comment]
I think a semantic such as ```npm smoketest``` is a great idea. 

Perhaps this can be a nice way of setting a standard for "production tests" (integration test?) that are designed to be run on the published module as opposed to the full repo.

**Comment by TheAlphaNerd** [comment]
I think #9 will solve this by allowing entries to specify the npm script to be run. I like the idea of putting the onus on citgm to manage a list that works as opposed to trying to herd cats.

Closing for now but feel free to reopen if you think I am being hasty
