### ISSUE TITLE
Can we test `full-icu`

### ISSUE THREAD

**Issue by srl295** [nodejs/citgm#142]
- …just verifying that it installs is fine. 
- Extra credit would be verifying that 

```
node --icu-data-dir=node_modules/full-icu -e "console.dir(Intl.DateTimeFormat('es',{month:'long'}).format(new Date(9E8)) === 'enero')"
```

… is truthy

**Comment by TheAlphaNerd** [comment]
@srl295 does this require that node is compiled with full-icu?

Would adding the full-icu module + test suite be sufficient?

CITGM primarily grabs a tarball and runs `npm test`

If there is some setup that needs to go on we could in theory make a meta module that has full-icu as a dep and runs a series of tests

**Comment by srl295** [comment]
No requirement. Any node is fine. It should install without err. 

I can add a test target to it for self check.

**Comment by TheAlphaNerd** [comment]
Does full-icu have a test suite?

**Comment by srl295** [comment]
It will soon!

**Comment by srl295** [comment]
^^

**Comment by srl295** [comment]
[full-icu-test](https://www.npmjs.com/package/full-icu-test) has an `npm test` script that will test everything.. expected result:

```
+ Congrats, you have the Intl object.
OK! Formatted January in Spanish, === enero
```

**Comment by srl295** [comment]
Hmm… ping @TheAlphaNerd again or fix it myself… decisions…

**Comment by srl295** [comment]
Next up: `full-icu-test-test`… :meta:
