### ISSUE TITLE
Testing deprecations

### ISSUE THREAD

**Issue by jasnell** [nodejs/citgm#149]
It would be fantastic to be able to run citgm with the `--throw-deprecation` flag set so that we can kick off CITGM runs that test the impact of new hard deprecations.

**Comment by TheAlphaNerd** [comment]
Will dig into this... the tricky part will be passing the node flag to the npm script

@zkat @othiym23 @iarna is there an easy way to pass an npm script a flag to pass to node itself?

**Comment by othiym23** [comment]
Nope. The easiest thing to do would be to write a `node` wrapper script that calls the actual node process with whichever flags you want set.

**Comment by bengl** [comment]
Now that https://github.com/nodejs/citgm/commit/67ae086fd744426d376c45f83d6835d8a2243c34 has landed, this can be done for the the `npm test` step only, bypassing it for the install (if desired).

**Comment by MylesBorins** [comment]
@jasnell it would likely be simpler to implement this feature in CI. Do you see value in having it as a feature in CITGM?

**Comment by jasnell** [comment]
There are a couple of alternatives we can pursue. If/when https://github.com/nodejs/node/pull/10116 lands, we can use the redirect warnings environment variable to more easily track deprecations emitted during a test run; or, we can take advantage of Node.js obscure mechanism for inserting pre-loaded modules to install a `process.on('warning')` hook.

**Comment by targos** [comment]
Could we use `NODE_OPTIONS` to do that?
