### ISSUE TITLE
npm engines support

### ISSUE THREAD

**Issue by jasnell** [nodejs/citgm#15]
One additional check we may need to perform is a quick check against `engines` in the package.json to make sure that the version of the module being tested will be compatible with the version of node used. Leaving this here as a remind to get that added in.

**Comment by TheAlphaNerd** [comment]
@jasnell currently the installation will fail and the job will be considered unsuccessful if the version of node is not supported. We should likely skip rather than fail in that case

**Comment by TheAlphaNerd** [comment]
closing
