### ISSUE TITLE
Add modules that include natively compiled code

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/citgm#162]
We all want to see V8 5.1 land in node v6 lts right?

Please suggest some modules that we should be testing!

**Comment by ljharb** [comment]
leveldb / leveldown, node-sass, mongodb?

**Comment by jbergstroem** [comment]
- bcrypt: https://github.com/ncb000gt/node.bcrypt.js/
 - ref: https://github.com/TooTallNate/ref
 - time: https://github.com/TooTallNate/node-time

**Comment by targos** [comment]
canvas: https://github.com/Automattic/node-canvas

**Comment by targos** [comment]
Maybe [oracledb](https://github.com/oracle/node-oracledb) for corporate users.

**Comment by joaocgreis** [comment]
I am working on adding native modules to CITGM (a bit slow atm but I'll get back to it), here is my current list: https://github.com/janeasystems/citgm/commit/6dbf44cfc5b32da1fe27ceb3774deb2dcbe340b9 . Some require changes to CITGM, but most are straightforward to add. It's based on a list of the most downloaded from npm, probably a bit outdated.

**Comment by addaleax** [comment]
ffi: https://github.com/node-ffi/node-ffi

**Comment by Qard** [comment]
[bson](https://www.npmjs.com/package/bson), [pg-native](https://www.npmjs.com/package/pg-native), [serialport](https://www.npmjs.com/package/serialport)

**Comment by evanlucas** [comment]
[couchbase](https://github.com/couchbase/couchnode)

**Comment by mscdex** [comment]
[`hiredis`](https://github.com/redis/hiredis-node)

**Comment by evanlucas** [comment]
ah forgot about [oniguruma](https://github.com/atom/node-oniguruma)

**Comment by rgbkrk** [comment]
Zmq - https://github.com/JustinTulloss/zeromq.node

Pretty please

**Comment by TheAlphaNerd** [comment]
adding sqlite
