### ISSUE TITLE
Vinyl-fs flaky on ubuntu + debian

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#168]
adding to flaky list will dig in more soon

/cc @phated

**Comment by phated** [comment]
Link to failing tests?

**Comment by TheAlphaNerd** [comment]
@phated here is a new job testing on vinyl-fs.

**Comment by phated** [comment]
Does that CI allow us to chown?

**Comment by TheAlphaNerd** [comment]
I'm not 100% tbqh

/cc @jbergstrom

**Comment by jbergstroem** [comment]
chown how? tests are run by a user and setuid:ing to anything but that user won't work.

**Comment by MylesBorins** [comment]
going to close this an open a meta thread
