### ISSUE TITLE
refactor for consistent output

### ISSUE THREAD

**Issue by jasnell** [nodejs/citgm#17]
one of the current shortcomings of the tool is that it takes whatever the modules npm tests generates and just pipes those to stdout, which means in order for us to know if there are any failures, we have to go digging. Which is time consuming. The tool needs to be refactored to generate consistent usable output. /cc @thealphanerd

**Comment by TheAlphaNerd** [comment]
So considering that we are going to be having many different testing frameworks outputting all sorts of different results I can think of a couple different ways this problem could be approached.

1) Use transforms to get all output in a consistent format such as TAP, at which point various reporters could be used to clean up output

2) Make default output non verbose and generate naive binary output based on passing / failing. Again, if this output is standardized around TAP or something similar we can use an off the shelf tool to sanitize output.

**Comment by TheAlphaNerd** [comment]
Closing as fixes to logging have landed
