### ISSUE TITLE
CI integration

### ISSUE THREAD

**Issue by jasnell** [nodejs/citgm#18]
The tool needs to be integrated into the CI environment so that fully automated runs are possible. The current design of the tool does not make that easy. /cc @thealphanerd

**Comment by TheAlphaNerd** [comment]
Can you elaborate on what in particular makes the tool not CI friendly?

Do you think the work lives more on the dev ops side or requires some re architecture.

**Comment by TheAlphaNerd** [comment]
This could also be further complicated by packages that have tests that need to run in the browser (as I just notices happens with async)

**Comment by jasnell** [comment]
As well as tests that require additional resources. Mongo for instance.

**Comment by jasnell** [comment]
The key challenges with the CI automation are (a) the output is less than useful and generally impossible to parse and (b) the list of modules to be tested needs to be hard coded into the jenkins job config. It's rather... irritating.

**Comment by rvagg** [comment]
> the list of modules to be tested needs to be hard coded into the jenkins job config

Not true, we could hard code it into citgm or the node repo, or somewhere else that we can edit without having to touch Jenkins, we just need to execute it from Jenkins in a way that picks up that list. I'd prefer we do that sooner rather than later because the more logic in Jenkins the harder it is to critique and contribute for everyone but Jenkins admins (there are maybe 5 or 6 of us).

**Comment by TheAlphaNerd** [comment]
I vote for having it embedded in CITM. there could be a single flag to run the gamut of smoke tests

```citm --smoketest```

**Comment by mhdawson** [comment]
+1 for having a base list embedded in CITGM.  If testing some modules requires additional setup/resources (like a database) we might want a couple of options like --smoketest-basic and --smoketest-full

**Comment by jasnell** [comment]
Hard coding the list within citgm could give a bit of a false sense of security as the ecosystem continues to evolve -- that is, we could end up missing new critical pieces that emerge.

**Comment by mhdawson** [comment]
I agree we have to keep a list up to date, but whether its under --smoketest or somewhere else I think we'd have the same problem.  Unless we keep it up to date we'll miss coverage that is needed

**Comment by TheAlphaNerd** [comment]
citgm-all has solved most of the problems that were mentioned in this issue.

closing in lieu of #10 where we can discuss Jenkins specific CI stuffs
