### ISSUE TITLE
Pedantic nitpicking

### ISSUE THREAD

**Issue by mightypenguin** [nodejs/citgm#185]
Btw you are aware that the actual saying is "Canary in a coal mine", not a gold mine?
I guess the advantage of naming this project that way is that there won't be any other search results.

https://en.wikipedia.org/wiki/Sentinel_species

I'm not seriously suggesting you rename your project. But it may be worth a note somewhere.
I have been following node for awhile and if there's some play on using the word "gold" (instead of coal) in reference to something, I didn't get it and others may need a hint as well.

**Comment by TheAlphaNerd** [comment]
@mightypenguin it is specifically gold mine, and that was a decision by @jasnell ... I'm pretty sure because "it sounds good"

Feel free to add something to the readme and send a PR if you like

**Comment by jasnell** [comment]
I picked `gold` literally because gold is shiny ;-)

**Comment by broofa** [comment]
53-year old me with a brain overflowing from having to remember a lifetime of exceptions to rules, stumbling onto this issue four years later...


![image](https://media0.giphy.com/media/DfTZWmFpLx3os/giphy.gif)

**Comment by jasnell** [comment]
![image](https://user-images.githubusercontent.com/439929/90185449-9b99ab80-dd6b-11ea-9bfe-c32d0f110188.png)
