### ISSUE TITLE
examples in readme don't work

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/citgm#19]
currently the examples in the readme include ```-v``` but do not include a loglevel, and as such they fail :cry: 

*  should there be a sane default?
* should citg inform individuals when specific options are used incorrectly?
  * is this a feature offered by commander?

**Comment by TheAlphaNerd** [comment]
updating the readme is also an option that could close this issue, but it doesn't address the overall concern of how incorrect options are handled

**Comment by TheAlphaNerd** [comment]
It would appear that the ```-l``` option when not given a path is failing as well (similarly silent)

**Comment by TheAlphaNerd** [comment]
So this has to do with the way in which commander parses arguments.
If an argument has an "optional" arg commander will parse the first string after it as the argument. In the case of ```citgm -v lodash``` we end up with lodash being passed as the argument to ```-v``` 

At this point commander never runs the action function, meaning that the value of mode is never set, and this code path gets executed --> https://github.com/nodejs/citgm/blob/master/bin/citgm#L55
Essentially dumping help into the terminal and exiting.

If the options are provided AFTER the module argument than everything works as expected

```bash
$ citgm lodash -vl
```

for the issue with verbosity we could potentially follow what npm does. 

-d / -dd / -ddd for various levels of verbosity as a shorthand
--loglevel <value> (value is required)

**Comment by TheAlphaNerd** [comment]
the way nopt in particular handles shorthands is what allows for this to work as expected

--> https://www.npmjs.com/package/nopt

it allows you to make options that require a value (with validation), and then to make shorthands that have an optional pre-assigned value. all options have two dashes (--) all shorthands have one (-)

ok... I'm taking a break from this bikeshed :D

**Comment by jasnell** [comment]
Yeah, this is one aspect of commander that I've never quite been happy with.
