### ISSUE TITLE
add -a append option to citgm-all

### ISSUE THREAD

**Issue by GeorgeAdams95** [nodejs/citgm#193]
When we run our citgm tests we pre-create a tap file with useful meta data in about the jenkins job (etc). The problem with citgm is that it overwrites this file. However easy it would be to just append this data afterwards, it would be useful if we could just tell citgm-all that we want to append using -a or something

**Comment by TheAlphaNerd** [comment]
@GeorgeAdams95 I think that this could be done by alternating between `readFileSync` and `appendFileSync` [in the reporter](https://github.com/nodejs/citgm/blob/master/lib/reporter/tap.js#L31)

Would you be interested in submitting a Pull Request?

This does bring up some interesting problems with our current logging set up. I have discussed with @bengl before about a major refactor of the logging in CITGM, perhaps this is a bigger project you might be interested in.

**Comment by GeorgeAdams95** [comment]
Yes i'm happy to put together a pull request. I was speaking with @gibfahn about whether we could find a way to append to a tap file test-by-test rather than as one batch at the end but obviously this would be something more major. But yeah, I would be interested in a project like that

**Comment by GeorgeAdams95** [comment]
landed in 640556b
