### ISSUE TITLE
VM Automation

### ISSUE THREAD

**Issue by jasnell** [nodejs/citgm#2]
`citgm-dockerify` is great for testing on linux, not so great for automating against other platforms.
It would be ideal to have the ability to automate launching VM images, pushing a node install, then running a (or multiple) citgm test on the launched image. Using something like https://www.npmjs.com/package/pkgcloud and cloud-init ought to do the trick. Just need to play around with it to get it working.

**Comment by TheAlphaNerd** [comment]
I'm going to close this as out of scope. For now it makes sense to me that citgm focuses on automating the test running.
