### ISSUE TITLE
Windows CITGM test failures

### ISSUE THREAD

**Issue by GeorgeAdams95** [nodejs/citgm#201]
NODE 6.7.0
I am having problems running citgm on windows. I am able to install the modules but all of the tests are failing with the following error:
```
# undefinedC:\Users\jenkins\AppData\Local\Temp\usenode.jenkins0\node-v6.7.0-win-x64\npm.CMD:1
# (function (exports, require, module, __filename, __dirname) { :: Created by npm, please don't edit manually.
# ^
# SyntaxError: Unexpected token :
# at Object.exports.runInThisContext (vm.js:76:16)
# at Module._compile (module.js:528:28)
# at Object.Module._extensions..js (module.js:565:10)
# at Module.load (module.js:473:32)
# at tryModuleLoad (module.js:432:12)
# at Function.Module._load (module.js:424:3)
# at Module.runMain (module.js:590:10)
# at run (bootstrap_node.js:394:7)
# at startup (bootstrap_node.js:149:9)
# at bootstrap_node.js:509:3
```

This is happening on windows 7 and 2012 (x64 and x86)

**Comment by TheAlphaNerd** [comment]
@GeorgeAdams95 can you describe your set up? 

Is this having installed Node.js for the installer?
What terminal emulator are using?
What command are you running to cause this error?
Are you able to install other modules with npm?
Do other projects work as you would expect them to?

**Comment by GeorgeAdams95** [comment]
Sure
We download the zip file of IBM node, extract it and add it to the path
We use git bash
We run `npm install citgm`
and then we run citgm-all
We are able to install the modules with npm manually

**Comment by TheAlphaNerd** [comment]
have you tried installing the module globaly?

**Comment by GeorgeAdams95** [comment]
yes same error, it is worth noting that I am using a custom lookup.json file though but I am just checking with the default json

**Comment by GeorgeAdams95** [comment]
yep same error when running with the default json

**Comment by TheAlphaNerd** [comment]
can you try

`$ npm install --global thealphanerd/citgm#master`

and let me know what happens

**Comment by GeorgeAdams95** [comment]
interesting, yes that worked

**Comment by GeorgeAdams95** [comment]
oh wait, you edited the comment, the previous one definitely worked

**Comment by GeorgeAdams95** [comment]
ahh, i'm being an idiot, you didn't make a new release yesterday did you?

**Comment by TheAlphaNerd** [comment]
I just made a new release, 5 seconds ago off master. Everything should work now 🎉

**Comment by GeorgeAdams95** [comment]
sweet thanks, i'll let you know

**Comment by TheAlphaNerd** [comment]
@GeorgeAdams95 please reinstall one last time, I just cut one more patch, and it should have windows working now.

**Comment by TheAlphaNerd** [comment]
Closing for now as it appears fixed. Please keep us updated on testing

**Comment by GeorgeAdams95** [comment]
resolved
