### ISSUE TITLE
Forever module logs building up

### ISSUE THREAD

**Issue by GeorgeAdams95** [nodejs/citgm#208]
The forever module by default places its logging info in $HOME/.forever

This is not ideal as it makes cleaning up much harder.

This can be overcome by running `export FOREVER_ROOT=$PWD/forever-logs` (or something similar)

We can either add an option to the lookup.json to run a shell script before executing and/or this could be a change that could be made to the forever module

**Comment by TheAlphaNerd** [comment]
unfortunately there is not much that we can do at the current moment. We do not yet have any way of running custom code for the install of a particular module.

Two courses of action that could be taken include

* adding a new option to the lookup
* adding something to the forever test suite to not use the log in the home directory.

@GeorgeAdams95 is this something you are interested in doing?

**Comment by GeorgeAdams95** [comment]
@TheAlphaNerd, I'd really love to add a way to run code before testing the suite so yeah I'll try and take a look at this some time

**Comment by gibfahn** [comment]
Forever issue raised: https://github.com/foreverjs/forever/issues/889

**Comment by TheAlphaNerd** [comment]
@GeorgeAdams95 can you make an issue for the feature request?

**Comment by GeorgeAdams95** [comment]
sure
