### ISSUE TITLE
Add env variables feature to json

### ISSUE THREAD

**Issue by GeorgeAdams95** [nodejs/citgm#209]
I want to be able to run bash script before citgm starts testing the module.

We could add a tag to the json called preBuild or something and just pass in a script to run

**Comment by TheAlphaNerd** [comment]
so one thing that could get a bit untenable would be maintaining a long list of various scripts. One thing we have been trying to avoid is a bespoke setup for all the different modules

One thing that may be a nice half way point would be an "envVar" object that could include environment variables to be passed. Thoughts?

**Comment by GeorgeAdams95** [comment]
yes that would a good idea, i'll take a look tomorrow

**Comment by GeorgeAdams95** [comment]
landed in 640556b
