### ISSUE TITLE
Run CitGM on more platforms in CI

### ISSUE THREAD

**Issue by gibfahn** [nodejs/citgm#210]
Issue to track getting CitGM enabled on as many platforms as possible.

### Possible platforms:
 - [ ]  FreeBSD
 - [ ]  CentOS
 - [x]  AIX
 - [x]  LinuxONE (a.k.a. s390)
 - [x]  Windows 

### What we need to do
 - Refactor the CitGM job to separate out platform-specific bits
   - Handle `make -> gmake` on AIX  
 - Add checks for unsupported versions (e.g. AIX pre-V6)

**Comment by joaocgreis** [comment]
@bzoz and I are working on adding Windows, shouldn't take long now.

**Comment by gibfahn** [comment]
@joaocgreis Is there an issue or something I could have a look at? I'd be interested to see how you're doing it. We've been running CitGM on windows for about 6 months now, we're just using Git bash and keeping everything else the same. Seems to work pretty well.

**Comment by joaocgreis** [comment]
Most of the work we're doing is to test native modules, it's a huge pain point on Windows and we want to improve CITGM there. Non-native modules are mostly ok.

**Comment by gdams** [comment]
okay so I have put in a few flaky tags and have now got clean runs on:

- LinuxONE (a.k.a. s390)
- ppc (big endian)

https://ci.nodejs.org/job/gibfahn-citgm-smoker-more-platforms/96/

I'm going to therefore add these platforms to the CI Smoker runs unless anyone objects?

CC @MylesBorins @gibfahn @mhdawson

**Comment by mhdawson** [comment]
+1 from me :)

**Comment by MylesBorins** [comment]
+1 we can remove them if they prove problematic. Would you be up for doing an audit of the current pass / fail / flake for current supported platforms?

**Comment by gdams** [comment]
@MylesBorins yes I'm happy to do that but I was hoping to get https://github.com/nodejs/citgm/pull/321 landed first as it should hopefully speed things up

**Comment by gibfahn** [comment]
+1 to adding the platforms.

**Comment by richardlau** [comment]
AIX was added some time ago. We are running on Centos on PPCLE.
