### ISSUE TITLE
Setup citgm-all to work with fips

### ISSUE THREAD

**Issue by gdams** [nodejs/citgm#212]
We (IBM) currently test our fips releases with an old citgm script that has been modified to work with fips. It would be good to get citgm working in the community.

The main difference is that with fips, we **require** certain modules to fail.

I propose that we setup a tag in the json object like `failFips` and then we can check if the node release is fips or not and then ensure that these specific modules fail if.

**Comment by TheAlphaNerd** [comment]
how is this different from the flaky flag we currently have?

**Comment by GeorgeAdams95** [comment]
flaky will be ignored if the modules passes won't it ? with fips it is essential that certain modules fail (if they pass then the fips isn't built correctly)

**Comment by GeorgeAdams95** [comment]
We need something like this: https://github.com/nodejs/node/blob/master/tools/test.py#L1331
