### ISSUE TITLE
Prevent citgm-all from passing when path to lookup is incorrect or when json contains errors

### ISSUE THREAD

**Issue by GeorgeAdams95** [nodejs/citgm#217]
At the moment if I run `citgm-all -l wrongpathtojson.json` I still get `The smoke test has passed.`
Also, if my json has an error, citgm will also pass.

We need to try and do some pre-checks on the lookup.json before running citgm-all

**Comment by TheAlphaNerd** [comment]
setting to a path that doesn't exist should be an error

https://github.com/nodejs/citgm/blob/master/lib/lookup.js#L41
https://github.com/nodejs/citgm/blob/master/lib/lookup.js#L63

Want to write a test that fails and then attempt to fix it?

**Comment by GeorgeAdams95** [comment]
yeah sure

**Comment by GeorgeAdams95** [comment]
fixed here: https://github.com/nodejs/citgm/pull/218
