### ISSUE TITLE
IBM Modules currently tested in a separate lookup.json

### ISSUE THREAD

**Issue by GeorgeAdams95** [nodejs/citgm#221]
IBM currently tests citgm-all with a series of IBM Modules. We have been working to get these all passing:
[appmetrics](https://github.com/RuntimeTools/appmetrics) - fully working
mqlight -fully working
[node-red](https://github.com/node-red/node-red) - working (flaky on aix- pending fix https://github.com/node-red/node-red/issues/1049)
[ibm_db](https://github.com/ibmdb/node-ibm_db) - requires a db2 instance so not a very good candiate at the moment

**Comment by GeorgeAdams95** [comment]
mqlight and node-red are both on github.ibm.com so we would need to get the tests from npm as this isn't externally accessible

**Comment by Fishrock123** [comment]
I don't think we should cater too much to one vendor or another, we need to be testing what people depend on the most.

**Comment by TheAlphaNerd** [comment]
closing for now, we can revisit specific modules I'm the future
