### ISSUE TITLE
React Github Tarball is 45MB

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#235]
This only just got on my radar. Do we want to continue supporting a 45 mb download per run?

**Comment by mikeal** [comment]
Why is the tarball so big? Is their repo really large and their module actually quite small?

**Comment by MylesBorins** [comment]
The docs are 50MB

**Comment by mikeal** [comment]
Their npm tarball is only like 600K but doesn't include their tests :(

I think it's important to keep testing react and having a project regularly produce a tarball with "tests but no docs" is a pretty specific edge case to expect projects to do in order to be supporting in citgm.

**Comment by MylesBorins** [comment]
to be honest I fully support then shipping the docs. we will be shipping a
multithread patch soon which will make this more an issue of bandwidth than
halting all the things
