### ISSUE TITLE
ember-cli set to skip

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/citgm#236]
Latest release and master are failing on all versions of node

**Comment by nathanhammond** [comment]
Latest release should work again as of about 10 seconds ago. `master` was broken by other CI drift I wasn't responsible for and may already work again. @stefanpenner and @hjdivad are on it.

**Comment by TheAlphaNerd** [comment]
@nathanhammond I'll dig into this in a little bit, thank you for being quick to respond :D

**Comment by nathanhammond** [comment]
I now have a PR up that you can press "merge" on once you get confirmation from @stefanpenner or @hjdivad.

This is _awesome_ and I'm super-happy to have made the cut for being part of this test suite.

**Comment by TheAlphaNerd** [comment]
rad! glad the process is working
😁
