### ISSUE TITLE
mark Async as flaky until timeout errors are fixed

### ISSUE THREAD

**Issue by GeorgeAdams95** [nodejs/citgm#260]
I am seeing a lot of failures with Async at the moment. They seem related to this issue: https://github.com/caolan/async/issues/1322. We should mark Async as flaky for everything until this has been rectified.

**Comment by TheAlphaNerd** [comment]
sgtm. want to send a pr?

**Comment by GeorgeAdams95** [comment]
@TheAlphaNerd done
