### ISSUE TITLE
Add native modules to CITGM

### ISSUE THREAD

**Issue by bzoz** [nodejs/citgm#268]
Continuing work from https://github.com/nodejs/citgm/pull/230, I would like to add following native modules to CITGM. They are all one of the most popular modules that use native addons:

- `bufferutil`
- `utf-8-validate`
- `v8-profiler`
- `v8-debug`
- `thread-sleep`
- `contextify`
- `hiredis`
- `weak`

I'll open a PR for each module, leaving this as a space for meta-discussion (if needed).

**Comment by TheAlphaNerd** [comment]
@bzoz if each are tested and working locally without any special environments I see no reason you could not submit a single PR.

**Comment by GeorgeAdams95** [comment]
@bzoz please combine your pr's into one single PR as this will make testing on the CI much simpler

**Comment by TheAlphaNerd** [comment]
@bzoz I closed the various PR's that you opened as it would be too much work to test each individually. Can you please submit a single PR that includes all the modules you would like to add. We can then do a single run of CITGM and see where we are at.
