### ISSUE TITLE
Add windows support to NPM test

### ISSUE THREAD

**Issue by gdams** [nodejs/citgm#276]
currently `npm test` does not work on CITGM. I have been working on getting support added but have hit a few issues. I have been playing around with using AppVeyor as an separate CI that we could use to manage PR's alongside Travis.

https://github.com/GeorgeAdams95/citgm/pull/3

Current Issues are:
We cannot run the SIGINT test as windows can't handle these.
All of our tests that run alternative .sh scripts fail.

We could either add support for having separate windows scripts OR we could perhaps setup skips on some of the tests?

@TheAlphaNerd any ideas?

**Comment by TheAlphaNerd** [comment]
I mean we could throw a platform if statement around all the tests that fail on windows.

Can you elaborate on the scripts failing

**Comment by GeorgeAdams95** [comment]
It can't run a shell script if it's windows.. Not sure how we'd get around that

**Comment by TheAlphaNerd** [comment]
can you link to the specific tests

**Comment by GeorgeAdams95** [comment]
this is one example: https://github.com/nodejs/citgm/blob/master/test/fixtures/test-envVar.sh

**Comment by GeorgeAdams95** [comment]
okay so I have skipped the broken tests for now. CI results are here: https://ci.appveyor.com/project/GeorgeAdams/citgm/build/1.0.47. Weirdly won't pass on node 4? I suggest that we look at adding alternative windows scripts that run either powershell or batch files

**Comment by bzoz** [comment]
@gdams maybe drop `scriptWin` and skip all tests withs `script` for now? It would be nice to be able to run tests on Windows

**Comment by bzoz** [comment]
Looks like this can be closed - `npm test` runs just fine on Windows.
