### ISSUE TITLE
Fix passing a directory to CitGM

### ISSUE THREAD

**Issue by gibfahn** [nodejs/citgm#280]
It should be possible (and apparently used to be possible) to pass citgm a directory and have it clone to a temp dir, run `npm i && npm test`, and report the results. That doesn't seem to be working at the moment.

Once we've re-enabled `citgm /path/to/module`, we can then use it to test vendored dependencies in node (as long as they're npm packages). This includes the inspector and npm itself.

**Comment by gdams** [comment]
This is already working: you can use `citgm ./my-module`
