### ISSUE TITLE
Alias -v to --version

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#306]
This alias should exist, likely in `lib/common-args.js`

**Comment by MylesBorins** [comment]
whoops... we currently have `-v` alias'd to verbosity... that would be annoying to change. Closing... sorry for noise 🎉

**Comment by gibfahn** [comment]
If we're going to be releasing a major bump, it might be worth considering something like `-V` for verbosity and `-v` for version, `-v` as version is pretty well established right?

**Comment by MylesBorins** [comment]
it is a nice to have but would break ever CI instance of citgm... I'm not convinced it is worth it
