### ISSUE TITLE
Gyp fails when running on prerelease version

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/citgm#31]
```
"pre" versions of node cannot be installed
```

What is the best practice to avoid this?

/cc @jasnell @rvagg

**Comment by bnoordhuis** [comment]
Pass `--nodedir /path/to/src` to node-gyp or set `npm_config_nodedir` in the environment.

**Comment by TheAlphaNerd** [comment]
@bnoordhuis ```--nodedir /path/to/src``` should be the node repo dir?

**Comment by bnoordhuis** [comment]
Correct.

**Comment by TheAlphaNerd** [comment]
looks like there is already an option for this.. closing
