### ISSUE TITLE
Add George Adams to the citgm-admins list.

### ISSUE THREAD

**Issue by mhdawson** [nodejs/citgm#317]
As per https://github.com/nodejs/build/pull/554 we have now set up the citgm-admins group and this allows members of that team to configure/update citgm jobs.

George Adams is a collaborator in the citgm repo and needs to be able to configure some of the jobs he is working on.

Provided he gets the thumbs he can also test out that things have been setup correctly.  As per the suggested criteria:

* Does the scope and size of the need justify providing access.
  * Actively working on jobs, including adding parallelization and new platforms

*  Is the individual a Node.js collaborator? If so then access should be allowed provided the first point is satisfied.
   * Not a Node.js core collaborator, but is a collaborator in the citgm repo

*  Length and consistency of involvement with Node.js working groups and/or community.
   * Has been working in community and on citgm for many months

* Consequences to the individual in case of mis-behaviour. For example, would they potentially lose their job if they were reported as mis-behaving to their employer? Would being banned from involvement in the Node.js community negatively affect them personally in some other way?
   * Works for IBM, job tied to working in Node.js community so being banned would definitely negatively affect him

* Are there collaborators who work with the individual and can vouch for them.
   * I've worked with him + will vouch
   * Myles has been working with him and likely can as well.

**Comment by MylesBorins** [comment]
+!

**Comment by MylesBorins** [comment]
added

**Comment by gibfahn** [comment]
Belated +1
