### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/citgm#341]
@gdams there have been a few changes over that past 3 weeks but no updated release, would it be possible to do them more often like @MylesBorins did?

**Comment by MylesBorins** [comment]
there was a release 6 days ago. currently only @jasnell and I have the release but for npm, but we can definitely on board the other collaborators. I'll put together a release guide

**Comment by jasnell** [comment]
+1 for onboarding other releasers. Also, given that I haven't been directly
involved in citgm dev or release for a while, feel free to remove me from
the list of releasers.

**Comment by gdams** [comment]
+1 would be great to be able to have access to cut releases myself rather than having to Myles

**Comment by Fishrock123** [comment]
Err, did you just tag a commit? I don't see a release commit anywhere.

**Comment by MylesBorins** [comment]
@Fishrock123 indeed v1.10.0 was published 13 days ago, both tagged and pushed to github and published to npm

**Comment by gdams** [comment]
Release guide has now been added
