### ISSUE TITLE
Jenkins CI

### ISSUE THREAD

**Issue by gdams** [nodejs/citgm#342]
We should look into creating a CI test for citgm on jenkins so that we can run `npm-test` on all of our platforms. Node core are already doing this and are exploring whether they can use the GitHub bot to automatically kick off the jobs. This would also hopefully prevent some of the flakiness that we are seeing with Travis

**Comment by MylesBorins** [comment]
@gdams technically we could just run the citgm job 
¯\\\_(ツ)\_/¯

can you point me towards the thread where they are talking about doing this for core. AFAIK this was not done for security and resource reasons

**Comment by gdams** [comment]
https://github.com/nodejs/github-bot/issues/82 The key thing is that a module admin must type `safe to test` or something before the bot runs the CI

**Comment by gdams** [comment]
https://github.com/nodejs/github-bot/pull/123

**Comment by gdams** [comment]
closing as #358 is more relevant
