### ISSUE TITLE
Manually specify version in lookup.json

### ISSUE THREAD

**Issue by gdams** [nodejs/citgm#346]
This is something that has been discussed before. Should we hard code the version into the lookup.json?

Pros:
- New module releases don't break the smoker job
- Helps us stay on top of flaky modules
- Encourages the module owners to fix failures to stay up to date in citgm

Cons:
- Module owners need to submit a PR to citgm when they cut a new release
- The lookup.json could quite quickly go out of date

I'm personally pro implementing this, we could perhaps have a verbose tag that logs when new versions are available

**Comment by MylesBorins** [comment]
Giant -1. There is no way to keep up with all the modules changing. Further while it may be "annoying" when things break, it is kind of the entire point. We need to be testing what people are getting when they run npm install

**Comment by gdams** [comment]
Haha, i'll go hide in a corner now ;)

**Comment by gibfahn** [comment]
There's also the issue that we can't pin the dependencies  of those modules (unless we start using shrinkwraps), so you can still be broken by a deps update. We've also seen issues where not updating the module caused breakage down the line, so I don't think there's any net gain here.

**Comment by gdams** [comment]
closing due to lack of interest
