### ISSUE TITLE
I would like to join the team

### ISSUE THREAD

**Issue by targos** [nodejs/citgm#352]
Hello, I'm interested in contributing more to the CITGM project and participate to code reviews.
/cc @nodejs/citgm

**Comment by gibfahn** [comment]
+1

**Comment by gdams** [comment]
I'm +1 with you joining but as I have discussed with @MylesBorins before, we need to start using an IRC/Slack channel to keep all the members up to date with changes.

**Comment by MylesBorins** [comment]
+1

**Comment by gdams** [comment]
@MylesBorins do you want to go ahead and add targos to the citgm team?

**Comment by MylesBorins** [comment]
Done + Done.

Welcome aboard @targos

**Comment by ericjjj** [comment]
can i join this team?  @MylesBorins

**Comment by gdams** [comment]
@ericjjj fancy creating a new issue?

**Comment by MylesBorins** [comment]
Hey @ericjjj generally we start by getting some contributions in to CITGM before inviting people to join the team
