### ISSUE TITLE
v1.x branch

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#354]
We've started work towards a v2.x milestone, one of the biggest changes being the introduction of es6 code.

Personally I am viewing this as a semver major change, as previous versions of `citgm` worked on v0.10 and v0.12

As such I have created a v1.x branch. This was branches off of v1.11.1, and has two cherry picked commits from master.

Just a quick note for collaborators, when landing code, if it is not semver major please backport to v1.x. Also can we please accurately use the Semver Minor and Semver Major labels on appropriate PRs... we will be able to rely on this for use branch diff to batch backports

Thanks!

**Comment by gdams** [comment]
CC @nodejs/citgm

**Comment by gibfahn** [comment]
@MylesBorins do we need to go back through existing PRs and mark their semverness?

**Comment by MylesBorins** [comment]
@gibfahn nope, I've already marked everything that has landed post v1.11.1

@gdams any issue in this repo already ping `nodejs/citgm` :P

**Comment by gibfahn** [comment]
>  any issue in this repo already pings `nodejs/citgm` :P

@MylesBorins but it doesn't go into the Participating bucket in the [web interface](https://github.com/notifications).

![image](https://cloud.githubusercontent.com/assets/15943089/23200145/a5b5e5cc-f8ca-11e6-9570-6bbbf365c3f2.png)

**Comment by MylesBorins** [comment]
@gibfahn INTERESTING. I was unaawre of that
