### ISSUE TITLE
node report flaky on v4

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#356]
We should figure out why, and if necessary set the flag

**Comment by richardlau** [comment]
@MylesBorins Do you have an example failure?

https://github.com/nodejs/node-report/pull/58 might be related (landed in node-report master ~14hrs ago).

**Comment by MylesBorins** [comment]
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/588/

**Comment by richardlau** [comment]
> https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/588/

Can confirm the node-report failures are the same ones that will be fixed by  https://github.com/nodejs/node-report/pull/58.

Cc. @rnchamberlain

**Comment by gdams** [comment]
@richardlau is this fixed now?

**Comment by richardlau** [comment]
Should be fixed in node-report 2.1.1.

**Comment by gdams** [comment]
Fixed
