### ISSUE TITLE
Should we add meta data on who to ping?

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#359]
When a module is failing we likely want to ping a specific individual... should we add this meta data to the lookup?

**Comment by gibfahn** [comment]
Might save some time (I assume https://github.com/nodejs/citgm/pull/357#issuecomment-281816293 is an example of when we'd use it).

Maybe a `"maintainers": ["user1", "user2"]` with Github usernames?

**Comment by gdams** [comment]
seems like a logical thing to do
