### ISSUE TITLE
--verbose option

### ISSUE THREAD

**Issue by richardlau** [nodejs/citgm#371]
So I appreciate this is a case of not reading the manual, but today I tripped over that `--verbose` doesn't do what I expect it to do, i.e. turn on verbose level output. It actually appears to do what I would expect a `--loglevel` option to do, i.e. it expects a level parameter. Indeed there's a similar, more appropriately named `--npm-loglevel` (but why is the short form of that `-q`?).

Since v2 is coming (https://github.com/nodejs/citgm/issues/354), would there be any traction to renaming the option in the semver-major?

**Comment by MylesBorins** [comment]
--npm-loglevel and --verbose actually do two different things. --npm-loglevel sets the loglevel in npm itself, where --verbose sets the loglevel of citgms output.

I'm +1 on adding --loglevel as an alias to --verbose but -1 to removing --verbose... no need to break stuff that works rn.
