### ISSUE TITLE
Add `native` tag to lookup.json for native modules

### ISSUE THREAD

**Issue by gibfahn** [nodejs/citgm#377]
Now that https://github.com/nodejs/citgm/pull/308 has landed, we should start adding tags for useful subsections of our tested modules. 

The first one that comes to mind is a `native` tag for native modules.

**Comment by richardlau** [comment]
node-report would be one of those that should be tagged `native`.

**Comment by gibfahn** [comment]
PR: https://github.com/nodejs/citgm/pull/378
