### ISSUE TITLE
Consistent node-sass failures on master

### ISSUE THREAD

**Issue by mscdex** [nodejs/citgm#389]
* **Node Version**: master
* **CitGM Version**: whatever node CI is using
* **Platform**: any

It seems that `node-sass` explicitly checks `process.versions.modules`, but currently the master branch has a module version (53) that is not in [their current modules version list](https://github.com/sass/node-sass/blob/5521bb6b870d0275d7e0e090ea6d7d9e71e17264/lib/extensions.js#L62-L71), so a couple of the binding tests fail every time.

Is there some way we can ignore these particular errors for `node-sass` or perhaps mark it as flaky on master?

**Comment by gdams** [comment]
we can definitely mark node-sass as flaky on master

**Comment by gibfahn** [comment]
@xzyfer could `node-sass` either support `master` or proceed if a later module version is found?

**Comment by xzyfer** [comment]
@gibfahn we can fix these failing tests. They shouldn't fail the way they are. I'll look into to it asap.

**Comment by xzyfer** [comment]
My apologies for the delay. I've just release node-sass@v4.5.1 which should address the issue described. We'll work on a more permanent solution so you don't run into this again with Node 9.

**Comment by mscdex** [comment]
Reopening this as this seems to be happening again, my guess is because the module version was bumped again due to the V8 5.7 upgrade.

ping @xzyfer

**Comment by xzyfer** [comment]
Will ship an update today. Will find time to make this more fault tolerant asap.

**Comment by xzyfer** [comment]
Published the fix in node-sass@v4.5.2

**Comment by mscdex** [comment]
Thanks!

**Comment by mscdex** [comment]
@xzyfer This is an issue again with node master, which currently has a `modules` version of `'55'`.

**Comment by xzyfer** [comment]
@mscdex patched in https://github.com/sass/node-sass/pull/1969 and accounted for the bump to 57. Will ship in 4.5.3 with in the hour.

**Comment by MylesBorins** [comment]
Woot!!

**Comment by xzyfer** [comment]
Published node-sass@4.5.3 with support for module version 55 and 57.

**Comment by tech4him1** [comment]
@xzyfer Will this be fixed for future versions, or will it still need to be upgraded every new Node version?

**Comment by xzyfer** [comment]
@tech4him1 this will be fixed for reals, but I'd be lying if put a date on it. We're working on a better solution.

**Comment by tech4him1** [comment]
@xzyfer Do you have an issue on node-sass that I can watch, or just here?
