### ISSUE TITLE
Add Caching layer to improve performance on multiple runs

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#39]
One of the largest bottlenecks right now is downloading tar balls and running `npm install`.

If we could smartly cache we could likely get away with only calling `npm rebuild`

This could likely be accomplished naively by not cleaning up the temp folders, but there might be a more elegant way.

**Comment by rvagg** [comment]
we could put tarballs in `~/.citgm`

**Comment by MylesBorins** [comment]
I feel like this isn't the job of CITGM. Another module could theoretically wrap npm and improve the caching story.
