### ISSUE TITLE
Associate the Node.js Foundation npm user with citgm package

### ISSUE THREAD

**Issue by jasnell** [nodejs/citgm#391]
Per TSC decision, a new Node.js Foundation [npm user](https://github.com/nodejs/TSC/issues/211#issuecomment-286540466) account has been created and should be associated with all foundation projects published as modules to the registry.

**Comment by MylesBorins** [comment]
Added `nodejs-foundation`

**Comment by gibfahn** [comment]
Looking at the linked issue, it seems that the idea is that the user account *can* be used if necessary (i.e. if the normal publishers all go AWOL) but that it's not intended for normal use. Is that correct?

**Comment by richardlau** [comment]
> 
> 
> Looking at the linked issue, it seems that the idea is that the user account _can_ be used if necessary (i.e. if the normal publishers all go AWOL) but that it's not intended for normal use. Is that correct?

Correct. https://github.com/nodejs/build/blob/master/doc/access.md#npm-management:

> Modules are managed as follows:
>
> * The [`nodejs-foundation`](https://www.npmjs.com/~nodejs-foundation) npm user, which is managed by the Build WG, is an administrator on all Foundation npm packages. It is the means to add or remove other module collaborators, and shouldn't be used to publish releases.
