### ISSUE TITLE
Run CitGM on AIX

### ISSUE THREAD

**Issue by gibfahn** [nodejs/citgm#396]
* **Node Version**: v6.x and up
* **Platform**: AIX

Now that we have the ramdisk set up on the AIX test machines (see https://github.com/nodejs/build/issues/661), we should add AIX to the smoker CI runs.

Part of https://github.com/nodejs/citgm/issues/210

**Comment by gdams** [comment]
LGTM

**Comment by gdams** [comment]
Will add now

**Comment by gibfahn** [comment]
@MylesBorins I added `-J` to [the default citgm options](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/).

**Comment by gibfahn** [comment]
@nodejs/citgm it looks like the `--tmpDir` option had been removed from the citgm jobs, causing the `/tmp` directory to fill up on the AIX machines and break the CI builds. Not sure how this happened, but if there are any issues with `--tmpDir` then we should discuss.
