### ISSUE TITLE
Browserify now has prefix in release name

### ISSUE THREAD

**Issue by gdams** [nodejs/citgm#398]
browserify 14.3.0 now contains a `v` in the version.

@feross is this intentional? (if so we can update out module lookup)

**Comment by feross** [comment]
Ugh, sorry I keep making this mistake since browserify is the only project I work on that omits the `v` prefix. It's happened before, so maybe a good idea to handle it in citgm? I'll fix it again this time, though :)

**Comment by MylesBorins** [comment]
Feel free to just include the prefix. We’ll patch in citgm and then it won’t be an issue again :D

**Comment by feross** [comment]
Okay, it's fixed – tag `v14.3.0` deleted. Tag `14.3.0` added.

**Comment by gibfahn** [comment]
>Feel free to just include the prefix. We’ll patch in citgm and then it won’t be an issue again :D

@feross: as @MylesBorins says, it's a really simple fix in CitGM, it sounds like it'll be easier to just change it in the next version. If you comment in here before you release, we'll update.
