### ISSUE TITLE
refed from nodejs/build: CITGM runs for 16 hours starving other jobs

### ISSUE THREAD

**Issue by refack** [nodejs/citgm#409]
* **Node Version**: `master`
* **CitGM Version**: 
* **Platform**: Our CI

How can I help?

![image](https://cloud.githubusercontent.com/assets/96947/26026364/97ff095e-37c7-11e7-9b76-67d331680014.png)

For example this one has been waiting for a fedore22 worker for 6 hours
![image](https://cloud.githubusercontent.com/assets/96947/26026395/feec050e-37c7-11e7-8766-715c277236e4.png)

Ref: https://github.com/nodejs/build/issues/719

**Comment by gibfahn** [comment]
So I ran on `v7.10.0` and [it took 90 minutes](https://ci.nodejs.org/job/citgm-smoker/777/)

The [next build](https://ci.nodejs.org/job/citgm-smoker/778/) ran on https://github.com/nodejs/node/pull/13011 and [was still hanging on fedora22 after 7 hours](https://ci.nodejs.org/job/citgm-smoker/778/nodes=fedora22/).

Last bit of output was this, but as we're running in parallel it's hard to say whether this module is the one that has issues.

```
verbose: esprima using-uid   | 1000                
verbose: esprima using-gid   | 1000                
verbose: esprima using-node  | /home/iojs/build/workspace/citgm-smoker/nodes/fedora22/smoker/bin/node
verbose: esprima using-npm   | /home/iojs/build/workspace/citgm-smoker/nodes/fedora22/smoker/bin/npm
verbose: esprima mk.tempdir  | /home/iojs/build/workspace/citgm-smoker/nodes/fedora22/citgm_tmp/2648f141-f522-42eb-be7d-1a1cda3d370c
info: lookup              | esprima             
info: lookup-found        | esprima             
info: esprima lookup-replace| https://github.com/jquery/esprima/archive/3.1.3.tar.gz
info: esprima npm:        | Downloading project: https://github.com/jquery/esprima/archive/3.1.3.tar.gz
info: esprima npm:        | Project downloaded esprima-3.1.3.tgz
info: esprima npm:        | npm install started 
verbose: esprima npm:        | Using temp directory: "/home/iojs/build/workspace/citgm-smoker/nodes/fedora22/citgm_tmp/2648f141-f522-42eb-be7d-1a1cda3d370c/npm_config_tmp"
verbose: esprima nodedir     | Using --nodedir="/home/iojs/build/workspace/citgm-smoker/nodes/fedora22/node"
error: acorn npm:          | npm-install Timed Out
error: failure             | Install Timed Out   
info: duration            | test duration: 602913ms
error: acorn done          | done - the test suite for acorn version 5.0.3 failed
info: esprima npm:        | npm install successfully completed
info: esprima npm:        | test suite started  
```

@refack is it just `fedora22` that seems to be having the problem?

**Comment by refack** [comment]
> @refack is it just fedora22 that seems to be having the problem?

It's just that `fedora22` is has a single instance so it popped up as starving everything else. I think I saw `osx1010` also starved.

**Comment by MylesBorins** [comment]
We have a time out mechanism in citgm… very odd that it is not working

**Comment by targos** [comment]
Anything actionable on this?

**Comment by refack** [comment]
I believe this was mitigated with https://github.com/nodejs/citgm/pull/441
