### ISSUE TITLE
npm installations timing out

### ISSUE THREAD

**Issue by mscdex** [nodejs/citgm#412]
* **Node Version**: master
* **CitGM Version**: ?
* **Platform**: all

In CI installation of many modules are timing out. At first I thought it had something to do with my PR, but then I discovered the same thing with the master branch. There are two modules (it seems like it's always the same two for some reason) that install just fine but fail for other reasons.

[Example](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/782/nodes=aix61-ppc64/testReport/)

**Comment by mscdex** [comment]
Nevermind, this is due to some bugs currently with async hooks in master. Ref: https://github.com/nodejs/node/issues/13045

**Comment by MylesBorins** [comment]
!!!

It worked!!!!

**Comment by mscdex** [comment]
@MylesBorins Well, indirectly ;-)

**Comment by MylesBorins** [comment]
@mscdex can you close this when it is fixed on master
