### ISSUE TITLE
Majors are cheap: Intent to ship v2.x

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#414]
We've been keeping 2.x at bay for reasons... I think we should just ship it, and then if we want to do another major we should just do it!

thoughts?

**Comment by targos** [comment]
+1
`npm i -g citgm` always installs the latest major so I don't think that will bother anyone.

**Comment by gibfahn** [comment]
:shipit:

**Comment by gdams** [comment]
let's get through the PR backlog and then cut v2.0.0?

**Comment by MylesBorins** [comment]
I've audited the backlog, AFAICT there are no semver majors that are currently outstanding (there are a handful of minors).

I intend to ship the 2.x release after the node 8.x release next Tuesday

**Comment by MylesBorins** [comment]
Done... congrats everyone!
