### ISSUE TITLE
add yarn to path in CI

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#415]
`ember-cli` now expects it in the path for the test suite to work. Should we add it to CI?

**Comment by gibfahn** [comment]
Ideally the `ember-cli` tests would skip the yarn tests if yarn wasn't available.

I'd rather not add another build-time dependency to CitGM, especially as the npm package [doesn't seem to be being updated](https://github.com/yarnpkg/yarn/issues/3078#issuecomment-297192266). However yarn [is in the node docker image now](https://github.com/nodejs/docker-node/pull/337), so maybe we should include it.

The [alternative install](https://yarnpkg.com/en/docs/install#alternatives-tab) looks interesting though, there's a tarball, and also a single js file. Not sure how downloading a tarball from the yarn website is safer than downloading a tarball through npm though...

>Note: Installation of Yarn via npm is generally not recommended. Installing Yarn with npm is non-deterministic, the package is not signed, and the only integrity check performed is a basic SHA1 hash, which is a security risk when installing system-wide apps.

**Comment by MylesBorins** [comment]
we could grab the tarball and then add to path... I'm personally comfortable with grabbing from official source

**Comment by SimenB** [comment]
Hiya. It'd be great to add Jest to CITGM, but it requires yarn. Are you opposed to a PR adding it? (See linked issue)

**Comment by BridgeAR** [comment]
@gibfahn I guess there might be even more packages relying on yarn. What do you think about the suggestion from @MylesBorins ?

**Comment by gibfahn** [comment]
>What do you think about the suggestion from @MylesBorins ?

No strong objection to adding the tarball to the path.

**Comment by targos** [comment]
We now have the yarn option that can be enabled selectively for modules that need it
