### ISSUE TITLE
moment requires grunt-cli globally installed

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/citgm#42]
PR sent to fix this

https://github.com/moment/moment/pull/2830

**Comment by TheAlphaNerd** [comment]
Moment has decided to not accept the PR and closed it, citing grunt-cli's docs advising to install grunt-cli globally.

I have opened an issue on the grunt-cli tracker to see if they would consider changing messaging regarding globally installing grunt-cli

https://github.com/gruntjs/grunt-cli/issues/90

**Comment by TheAlphaNerd** [comment]
My tenacity has paid off

**Comment by rvagg** [comment]
hah! well done @TheAlphaNerd!
