### ISSUE TITLE
suspected: process doesn't exit on rhel72-s390x

### ISSUE THREAD

**Issue by refack** [nodejs/citgm#423]
* **Node Version**: `master`
* **CitGM Version**: `1.11.3`
* **Platform**: rhel72-s390x

Last "successful" run was with `citgm@1.11.12` - https://ci.nodejs.org/job/citgm-smoker/nodes=rhel72-s390x/816/
Ever sinse `citgm@1.11.13` the run does not complete - https://ci.nodejs.org/job/citgm-smoker/nodes=rhel72-s390x/817/

List of runs: https://ci.nodejs.org/job/citgm-smoker/nodes=rhel72-s390x/
Cross-Ref: https://github.com/nodejs/build/issues/734

**Comment by MylesBorins** [comment]
Here is list of delta

* 48ea2f0 - (HEAD -> v1.x, tag: v1.11.13) 1.11.13 (20 hours ago)<Myles Borins>
* 7dc8077 - lookup: winston as flaky (20 hours ago)<Refael Ackermann>
* e8c3323 - Add sodium-native (20 hours ago)<Emil Bay>
* aee7642 - lookup: add zeromq (20 hours ago)<Kyle Kelley>
* 3fe7e6a - lookup: add node-gyp (20 hours ago)<Richard Lau>
* 2d86a07 - lookup: add 3rd-Eden to ws maintainers (20 hours ago)<Luigi Pinca>

Looks like sodium native was the last module to run, we could simply skip on that platform and see if it helps. Want to submit a PR?

**Comment by refack** [comment]
PR Ref: #424 
I cleaned the log, kept only `info: starting` and `info: * done` and found that `zeromemq` does not finish
https://gist.github.com/refack/1554480241ded629a0639a741db72cb1

**Comment by MylesBorins** [comment]
closed by da9e51e
