### ISSUE TITLE
watchify stuck on macOS

### ISSUE THREAD

**Issue by refack** [nodejs/citgm#427]
* **Node Version**: `master`
* **CitGM Version**: 1.11.14
* **Platform**: macOS

Run stuck during testing phase - https://gist.github.com/refack/cfffb44ab401d2fe6e7caae2f0e291f0
I'd rather not skip since it's a non-trivial test case (watchify@macOS).
Opening this issue mostly for reference...

Ref: https://github.com/nodejs/citgm/issues/426

**Comment by MylesBorins** [comment]
@refack we can skip on a per platform basis fwiw

**Comment by refack** [comment]
> @refack we can skip on a per platform basis fwiw

Yeah I know, but `watchify`@`macOS` is a good test (since we don't run on any other *BSD) and it's the first time I see it get stuck.

**Comment by MylesBorins** [comment]
I think we are good to close this for now
