### ISSUE TITLE
Add crc32-stream to modules

### ISSUE THREAD

**Issue by targos** [nodejs/citgm#429]
https://www.npmjs.com/package/crc32-stream (1.4 Mio downloads last month)

Affected by a regression in Node 8.0.0: https://github.com/nodejs/node/issues/13358

**Comment by gibfahn** [comment]
Could you list the requirements from [CONTRIBUTING.md](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md#submitting-a-module-to-citgm) here and how this meets them?

+1 to including this.

**Comment by targos** [comment]
@gibfahn Sure!

Hard requirements:
* [x] Module source code must be on Github.
  * https://github.com/archiverjs/node-crc32-stream
* [x] Published versions must include a tag on Github
 * https://github.com/archiverjs/node-crc32-stream/releases
* [x] The test process must be executable with only the commands npm install && npm test using the tarball downloaded from the Github tag mentioned above
  * tested myself
* [ ] The tests pass on supported major release lines
  * tests pass on v4, v6 and v7
* [x] The maintainers of the module remain responsive when there are problems
  * pull requests are merged within a few weeks
* [ ] At least one module maintainer must be added to the lookup maintainers field
  * to be done in the PR

Soft requirements:
* [x] The module must be actively used by the community
  * 1.4 Mio downloads last month

**Comment by ctalkington** [comment]
let me know if you need anything here as I'd love to help prevent or preempt issues in the future

**Comment by gdams** [comment]
this module is able to run on FIPS
