### ISSUE TITLE
remove ubuntu 12.04 from all citgm smoker runs

### ISSUE THREAD

**Issue by gdams** [nodejs/citgm#431]
We don't really need to run citgm on ubuntu 12.04 anymore. @gibfahn says that it has been removed from the node test commit flows for node 7 and above

**Comment by gibfahn** [comment]
See: https://github.com/nodejs/node-v8/issues/2

Skipped for Node 8 and above actually, but given that we're not planning to do any more releases of 7 it doesn't really matter.

**Comment by gdams** [comment]
@MylesBorins any objections?

**Comment by MylesBorins** [comment]
We still are doing v6 releases for a while.

**Comment by targos** [comment]
The groovy script handles this correctly

**Comment by richardlau** [comment]
Also for reference; https://github.com/nodejs/build/issues/1616
