### ISSUE TITLE
Current CI Failures

### ISSUE THREAD

**Issue by gdams** [nodejs/citgm#432]
## 6.10.3
ubuntu1604-64
- readable stream (no `/home/iojs/tmp/`) https://github.com/nodejs/build/pull/658

ubuntu1604-64
- node-sass (`Mixin bar takes 3 arguments but 4 were passed.`) request to remove ubuntu12: https://github.com/nodejs/citgm/issues/431

aix61-ppc64
- zeromq
- sqlite3

osx1010
- uglify-js
- node-sass (`Mixin bar takes 3 arguments but 4 were passed.`)

ppcle-ubuntu-1404
- uglify.js
- yargs (`no such file or directory, unlink './test/fixtures/yargs-symlink'`)
- zeromq
- sqlite3

ppcbe-ubuntu-1404
- yargs
- leveldown
- zeromg
- sqlite3
- sodium-native

**Comment by MylesBorins** [comment]
@gdams I'm not seeing a lot of notes here about why you have set a variety of these to flaky. uglify-js and node-sass failing on v6 is quite concerning considering they are tools run by people during dev

**Comment by gdams** [comment]
@MylesBorins I am planning to create issues to ping the developers.

**Comment by MylesBorins** [comment]
@gdams should we keep this open until then?

**Comment by BridgeAR** [comment]
This seems outdated and should be closed. If it is still an issue, it is still possible to reopen this.
