### ISSUE TITLE
Audit all skipped / flaky modules

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#435]
Since we have a new official release it seem like a good time to go through and audit all modules that are skipped / flaky

**Comment by gdams** [comment]
I am having to go through some of the platforms with a fine comb and work out what is still flaky

**Comment by MylesBorins** [comment]
you are a hero @gdams

**Comment by refack** [comment]
@gdams If you feel like adding stuff take a look at : https://github.com/nodejs/node/wiki/CITGM-status
tl;dr [this one](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/847/testReport/) is very close to `v8.0.0` but on `master`. [this one](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/849/) __is__ `v8.0.0`
the diff should be all flakes

**Comment by MylesBorins** [comment]
@gdams what is status on this?

**Comment by gdams** [comment]
working on it atm

**Comment by gdams** [comment]
okay here is a test run: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/156/

**Comment by MylesBorins** [comment]
are you going to audit release lines as well? v4 / v6 / v8

**Comment by gdams** [comment]
I will do, starting with v6
