### ISSUE TITLE
Should we add package-lock.json to .gitignore?

### ISSUE THREAD

**Issue by targos** [nodejs/citgm#451]
Since node 8 and npm 5, `npm install` creates a `package-lock.json` to lock the versions of dependencies that are installed.
They recommend to commit this file and that's what I usually do in other projects but I think we should gitignore it in CITGM. This will allow us to always test the latest version of our dependencies (especially in CI).

**Comment by MylesBorins** [comment]
+1

**Comment by gibfahn** [comment]
+1

**Comment by proweber1** [comment]
I think no. Because the CI is usually driven by an assembly that is checked for production, in this case it should be assembled with the same dependencies as the version that you have on the local host, in this way `package-lock.json` must always commit. I apologize for my bad english

**Comment by targos** [comment]
The thing is that `citgm` is a CLI tool that is usually installed with `npm install -g citgm` (even on our CI) and this ignores the `package-lock.json` file.

**Comment by proweber1** [comment]
@targos Ah. I'm sorry. I globally thought about the task of `CI` and the `lock` files

**Comment by jerinthomas1404** [comment]
`git rm package-lock.json`

**Comment by krishnaUIDev** [comment]
git rm package-lock.json and commit your message
