### ISSUE TITLE
ftp failing on 8.3.0

### ISSUE THREAD

**Issue by al-k21** [nodejs/citgm#466]
* **Node Version**: 8.3.0 (does not fail on 8.2.1)
* **CitGM Version**:  2.0.5
* **Platform**: Darwin

```bash
  132 passing (179ms)
  2 failing

  1) Object should retain references to written Objects:

      AssertionError [ERR_ASSERTION]: "o" has not been garbage collected
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/object.js:46:5)

  2) pointer should retain references to a written pointer in a Buffer:

      AssertionError [ERR_ASSERTION]: "child" has not been garbage collected
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/pointer.js:45:5)
```

**Comment by al-k21** [comment]
@mscdex do you know why is it failing?

**Comment by mscdex** [comment]
The output you're showing has nothing to do with the `ftp` module?

I do vaguely remember a citgm failure with `ftp`, but I think it had something to do with Date instances not matching. I think it may have something to do with changes in how ES6/ES7 now interprets date/time strings, but I am not 100% sure. I do not currently have time to look into it unfortunately.

**Comment by targos** [comment]
@mscdex see https://github.com/mscdex/node-ftp/pull/191
