### ISSUE TITLE
Request Being flakey

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/citgm#47]
Across different systems and versions we are having inconsistent results testing request

on centos 5 / 6

```
verbose: npm-test:           | not ok test-localAddress.js ......... 5/5
```

on ubuntu 1404

```
verbose:                     | Assert: "Test file timed out:                     
verbose:                     | test-localAddress.js",                            
verbose:                     | found: true                                       
verbose:                     | wanted: false                                     
verbose:                     | test-localAddress.js:0  
```

On OSX 10.10 there seems to be some sort of rate at which it randomly fails during the phantomJS stages

**Comment by jasnell** [comment]
@mikeal

**Comment by mikeal** [comment]
I don't know anything about the PhantomJS tests. You should log an issue on `request/request`, there's a good number of contributors there.

**Comment by mikeal** [comment]
You may want to log an issue in the request repo, there's quite a few contributors over there.

**Comment by TheAlphaNerd** [comment]
@mikeal there is another open issue which is why I closed this one. Planning to do a deeper dive on the flakeyness before the v7 release

**Comment by mikeal** [comment]
@TheAlphaNerd have there been any changes to the underlying http implementation in this release?

**Comment by TheAlphaNerd** [comment]
not that I know of. the flakyness on request has been happening since v4
and have primarily been due to the test suite in request
