### ISSUE TITLE
Audit Skipped modules

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#473]
To try and urge CITGM towards green for 8.x, and to help with the 9.x release I've begun skipping modules that we know to be failures on the module side rather than a problem with the platform

We should audit all modules that are skipping 

```
underscore: win32
request: aix
commander: win32
coffee-script: v4
pug: true
jquery: win32
eslint: v8,ppc
react: true
gulp: win32
ws: win32
ftp: >=8
spdy: win32
spdy-transport: win32
jsonstream: win32
mkdirp: v8
yeoman-generator: >=8
cheerio: win32
zeromq: s390,ppc
bcrypt: win32
time: win32,aix
ember-cli: true
electron-prebuilt: ppc
libxmljs: win32,>=8
radium: ppc,s390
ffi: win32
koa: <7,win32,rhel
acorn: win32
esprima: win32
```

**Comment by MylesBorins** [comment]
anyone wanna take this as an action item?

**Comment by targos** [comment]
# underscore

Still failing on Windows.
This is because `qunit-cli` does not support Windows. There is a [PR to add support](https://github.com/devongovett/qunit-cli/pull/12).

<details>

```
error:                       | > underscore@1.8.3 test C:\Users\targo\AppData\Local\Temp\39a1b1a6-45a1-43dc-ab22-e56877849401\underscore
error:                       | > npm run test-node && npm run lint
error:                       |
error:                       |
error:                       | > underscore@1.8.3 test-node C:\Users\targo\AppData\Local\Temp\39a1b1a6-45a1-43dc-ab22-e56877849401\underscore
error:                       | > qunit-cli test/*.js
error:                       |
error:                       |
error:                       | module.js:538
error:                       | throw err;
error:                       | ^
error:                       |
error:                       | Error: Cannot find module 'C:\Users\targo\AppData\Local\Temp\39a1b1a6-45a1-43dc-ab22-e56877849401\underscore\test\*.js'
error:                       | at Function.Module._resolveFilename (module.js:536:15)
error:                       | at Function.Module._load (module.js:466:25)
error:                       | at Module.require (module.js:579:17)
error:                       | at require (internal/module.js:11:18)
error:                       | at C:\Users\targo\AppData\Local\Temp\39a1b1a6-45a1-43dc-ab22-e56877849401\underscore\node_modules\qunit-cli\bin\qunit-cli:51:3
error:                       | at Array.forEach (<anonymous>)
error:                       | at Object.<anonymous> (C:\Users\targo\AppData\Local\Temp\39a1b1a6-45a1-43dc-ab22-e56877849401\underscore\node_modules\qunit-cli\bin\qunit-cli:50:7)
error:                       | at Module._compile (module.js:635:30)
error:                       | at Object.Module._extensions..js (module.js:646:10)
error:                       | at Module.load (module.js:554:32)
```

</details>

**Comment by targos** [comment]
# commander

Fails on Windows because it uses `make`.

**Comment by targos** [comment]
# gulp

Fails on Window because it uses [`jscs`](https://github.com/jscs-dev/node-jscs) with a glob pattern that does not work. `jscs` is unmaintained and has been merged with ESLint.

**Comment by targos** [comment]
I created a project to track this: https://github.com/nodejs/citgm/projects/1

I am adding all the currently skipped modules to it right now.

**Comment by MylesBorins** [comment]
thank you for doing this work @targos

**Comment by targos** [comment]
I checked 8 modules that are currently skipped on Windows and they pass on my machine (Windows 10, VS 2017). I don't think there is a way to run CI on Windows only ?
Opened https://github.com/nodejs/build/issues/1035 to ask for it.

**Comment by targos** [comment]
The list:
* ws
* spdy
* spdy-transport
* bcrypt
* acorn
* koa
* level

**Comment by targos** [comment]
I created 5 columns:

* __Skipped (fixable)__: modules that are skipped for an unknown reason or because of something that could be fixed (for example by a PR to the module).
* __Being fixed__: fixable modules that have an open PR for the fix
* __To unskip__: modules that can be unskipped.
* __Fixed__: put modules there after unskipping -> we could also remove the card?
* __Skipped forever__: modules that will never be unskipped (for example: uses a feature like async/await that will never run on Node <7)

**Comment by al-k21** [comment]
I will be interested to work on this.

**Comment by MylesBorins** [comment]
we can start thi up again some time
