### ISSUE TITLE
Update CoffeeScript

### ISSUE THREAD

**Issue by GeoffreyBooth** [nodejs/citgm#480]
A few things about CoffeeScript:
- CoffeeScript has moved on NPM from `coffee-script` to `coffeescript`.
- It is in version 2.0.1 now, which supports only Node 6+.
- The 1.x branch briefly had a test that failed in Node 4, but that was fixed in https://github.com/GeoffreyBooth/coffeescript/commit/85974776f65622e86dc3ad96327c1e559e1f69ca. (The module itself always worked in Node 4.) The current newest 1.x version, 1.12.7, should work with passing tests in Node 4 and probably older versions of Node as well.

So I don’t know how you want to handle this. The simplest solution would be to just change `coffee-script` to `coffeescript` and leave it at that, since the new `coffeescript` doesn’t support Node 4 and you already have the exception in place.

**Comment by MylesBorins** [comment]
Fixed and published in 2.0.9

**Comment by GeoffreyBooth** [comment]
Thanks!
