### ISSUE TITLE
Feedback from doing a release smoke test

### ISSUE THREAD

**Issue by cjihrig** [nodejs/citgm#5]
When I did the io.js 2.5.0 release, I used CITGM to do some smoke testing. The experience was generally positive. Some complaints / things that would be nice to have:

1. Some way to detect/filter/message about modules that try to download gyp headers, at least during the pre-release smoke test.
2. Some type of consistent output from the modules. This might be a pipe dream, and would probably require working with module authors. But it would be nice to just see `X out of Y tests passed`. It's also not obvious what breaks because of the platform and what is just broken in the module. I treated it as "oh there are a few failures, but the module still works."
3. A pre-release suite that runs a carefully selected subset of modules with some expected output might be a start.

**Comment by rvagg** [comment]
Re item 2, perhaps we can have the source tree checked out and available and `npm config set nodedir=/path/to/src` so that it just works without node-gyp? Alternatively `--nodedir=/path/to/src` works too during `npm install`.

**Comment by jasnell** [comment]
We can, at the very least, look into package.json for modules that have gyp install steps and warn accordingly. The nodedir bit works too. That can be enabled via a command line switch. I'll work on that a bit later this week. @cjihrig ... just so I know, which modules were you testing during your release smoke test?

**Comment by cjihrig** [comment]
I was running the ones listed in the README. I also ran the hapi tests separately.

**Comment by TheAlphaNerd** [comment]
I think the latest release covers gripes 1 / 3

Better error output is going to be difficult, as there is no consistency between testing suites. Let's move the discussion about that to #38
