### ISSUE TITLE
New resolution algorithm failing with jquery

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#514]
on osx I'm running the command

`citgm -v verbose jquery`

> info:    starting            | jquery
verbose: jquery using-uid    | 445283
verbose: jquery using-gid    | 5001
verbose: jquery using-node   | /Users/mborins/.nvm/versions/node/v9.2.0/bin/node
verbose: jquery using-npm    | /Users/mborins/.nvm/versions/node/v9.2.0/bin/npm
verbose: jquery mk.tempdir   | /var/folders/p9/jw8_3dz56mz6yxdfd778p6lr00dkv3/T/f22ef64c-2ee9-4676-ac89-fd090620b710
info:    lookup              | jquery
info:    lookup-found        | jquery
info:    jquery lookup-replace| https://github.com/jquery/jquery/archive/77d2a51d0520d2ee44173afdf4e40a9201f5964e.tar.gz
info:    jquery npm:         | Downloading project: https://github.com/jquery/jquery/archive/77d2a51d0520d2ee44173afdf4e40a9201f5964e.tar.gz
error:   failure             | Failure getting project from npm
error:   failing module(s)   |
error:   module name:        | jquery
error:   version:            | 3.2.1
error:   error:              | Failure getting project from npm
error:   error:              | undefined
error:   done                | The smoke test has failed.
info:    duration            | test duration: 1810ms

will dig into what is going on

/cc @targos

**Comment by targos** [comment]
jquery seems to be published from another repo: https://github.com/jquery/jquery-dist/tree/77d2a51d0520d2ee44173afdf4e40a9201f5964e

We cannot just force this repo in the lookup because it doesn't contain any test. I guess we need a way to force using the tag instead of gitHead in this case...
