### ISSUE TITLE
Release instruction are broken on npm 5.x (node 8.x +)

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#516]
In npm 5.x there was a change in behavior to `npm version` which makes updating the `package-lock.json` a necessary part of the command. As we .gitignore package-lock.json this blows up.

Currently I'm rolling back to 6.x to follow our instructions, but that is janky + no good.

We have a couple options here

1) change tool we use to version
2) start using package-lock.json

I am feeling like option 2 might be the best solution.

Thoughts?

**Comment by targos** [comment]
> As we .gitignore package-lock.json this blows up.

How exactly?

**Comment by MylesBorins** [comment]
We ignore it currently
https://github.com/nodejs/citgm/blob/master/.gitignore#L6

part of the lifecycle of `npm version` now is to update and check in the changes to the package-lock.json

**Comment by targos** [comment]
What about `npm version patch --no-package-lock`?

I would not be against checking in `package-lock.json` if we regularly upgrade our dependencies in it.

**Comment by MylesBorins** [comment]
I had not tried that option... That works as a third option... Just need to
update instructions

On Dec 4, 2017 5:15 PM, "Michaël Zasso" <notifications@github.com> wrote:

What about npm version patch --no-package-lock?

I would not be against checking in package-lock.json if we regularly
upgrade our dependencies in it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nodejs/citgm/issues/516#issuecomment-349124475>, or mute
the thread

**Comment by targos** [comment]
On a second thought, maybe that's a npm bug? If we choose to ignore the package-lock, it should not prevent us from publishing.

**Comment by gdams** [comment]
I going to say that option 2 makes more sense for us
