### ISSUE TITLE
Add ability to skip on preRelease node / master

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#517]
There are a bunch of modules that fail on master for a number of reasons outside of our control including

* missing binaries for phantomjs
* rigid dependencies such as mock-fs
* Simply broken and awaiting a fix

One issue is adding a flag for a specific release potentially won't be removed when that release is promoted unless we are on top of things... it also means we need to update for the new version number when we roll a new major for core. it would nice to see this process more streamlined.

**Comment by richardlau** [comment]
Could we use the existing tagging mechanism to mark the modules that should be skipped for -pre versions of Node.js?

**Comment by MylesBorins** [comment]
@richardlau the challenge is we don't want them to be skipped for pre's that are not tip of tree

**Comment by richardlau** [comment]
I wasn't suggesting automating the skipping -- Merely that the tagging could be used to indicate which modules to skip and then `citgm-all --excludeTags ...` used to skip them.

**Comment by gdams** [comment]
I'm with @richardlau on that, let's work out which modules are failing on pre releases and then we can add a tag that can be skipped for release runs
