### ISSUE TITLE
Including non-free code in the citgm-all runs

### ISSUE THREAD

**Issue by jugglinmike** [nodejs/citgm#538]
A contributor to [the JSHint project](https://github.com/jshint/jshint) recently [suggested](https://github.com/jshint/jshint/pull/3245) that JSHint be included in the `citgm-all` runs. As they point out, JSHint seems to satisfy this project's criteria, so I'm inclined to submit a pull request. However, JSHint is encumbered with [the non-free JSON license](https://www.gnu.org/licenses/license-list.html#JSON), and I'm wondering if that disqualifies it. Could a maintainer weigh in on this? Thanks!

**Comment by joyeecheung** [comment]
I believe in essence citgm just does `git clone`, `npm install` and `npm test`, and make sure the package's unit tests are not broken by changes in Node core. So it surely does use the software for good, not evil.

cc @MylesBorins about other license stuff...I am not a lawyer but the notice thing is part of most licenses of packages that we test here.

**Comment by joyeecheung** [comment]
Also, we already in a way test JSHint since it is run by a lot of packages's tests during linting, that's also why I discovered https://github.com/jshint/jshint/pull/3245 because JSHint is run by bluebird, .etc. That means we already download JSHint and run it during citgm-all.

**Comment by MylesBorins** [comment]
Also not a lawyer

CITGM doesn't ship any of the code in the lookup table, and is distributed with the MIT license.  A dive into the package.json of jshint suggests that it is dual licensed [MIT && JSON](https://github.com/jshint/jshint/blob/master/package.json#L79). It would appear that the use of JSHint by CITGM would fall under the terms of both licenses... but only if you were to not [use it for evil](https://tldrlegal.com/license/the-json-license)

Whimsy aside... I personally feel comfortable including JSHint in the lookup, especially if there is a consensus by the maintainers.

**Comment by gdams** [comment]
+1 on adding JSHint to the lookup table

**Comment by BridgeAR** [comment]
I think this issue is resolved and should be closed as the question is answered.

**Comment by jugglinmike** [comment]
Agreed. I'm dragging my feet on the follow-up, but that's beside the point.

Thanks, folks!
