### ISSUE TITLE
CITGM - eslint test only failure on PPC

### ISSUE THREAD

**Issue by mhdawson** [nodejs/citgm#55]
The CITGM testing shows a PPC specific failure for the npm tests on eslint. This is not a problem running the module (ie eslint itself does not have a problem) but because of dependencies in the test.

https://ci.nodejs.org/job/thealphanerd-smoker/21/nodes=ppcle-ubuntu1404/console

Myles and I have identified that the issue is a missing binary in the phantomjs module so we'll see what we can do to have that added. Looks like phantomjs chooses its platforms based at least partially on what Node needs so hopefully they will be receptive to adding the PPC binaries now that Node builds for those platoforms.

**Comment by TheAlphaNerd** [comment]
I manually built node on ppc. Cloned eslint. ran ```npm install``` and it has installed cleanly

Looks like this is the error, which may not be reported by citgm

```
Error: EACCES: permission denied, mkdir '/tmp/eslint/fixtures'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:856:18)
    at mkdirSyncRecursive (/home/myles/eslint/node_modules/shelljs/src/mkdir.js:11:8)
    at /home/myles/eslint/node_modules/shelljs/src/mkdir.js:63:7
    at Array.forEach (native)
    at _mkdir (/home/myles/eslint/node_modules/shelljs/src/mkdir.js:48:8)
    at /home/myles/eslint/node_modules/shelljs/src/common.js:186:23
    at Context.<anonymous> (/home/myles/eslint/tests/lib/cli-engine.js:69:9)
    at callFn (/home/myles/eslint/node_modules/mocha/lib/runnable.js:286:21)
    at Hook.Runnable.run (/home/myles/eslint/node_modules/mocha/lib/runnable.js:279:7)
    at next (/home/myles/eslint/node_modules/mocha/lib/runner.js:297:10)
    at Immediate._onImmediate (/home/myles/eslint/node_modules/mocha/lib/runner.js:319:5)
    at processImmediate [as _immediateCallback] (timers.js:392:17)
```

**Comment by TheAlphaNerd** [comment]
It looks like the phantomJS error might be specific to ppcbe-fedora20

**Comment by TheAlphaNerd** [comment]
For context

[eslint job ONLY for ppcbe-fedora20](https://ci.nodejs.org/job/thealphanerd-smoker/22/nodes=ppcbe-fedora20/console)

 * Failure appears to be phantomJS related

[eslint job ONLY for ppcle-ubuntu1404](https://ci.nodejs.org/job/thealphanerd-smoker/22/nodes=ppcle-ubuntu1404/console)

 * failure appears to be related to above error regarding permissions to /tmp

**Comment by TheAlphaNerd** [comment]
It appears that the tmpdir issues might have been system related as /tmp/eslint already exists owned by user iojs. I'm manually changing tmpdir and trying again.

**Comment by TheAlphaNerd** [comment]
It seems like the ppcle-ubuntu1404 tests are failing when calling to phantomjs

https://github.com/eslint/eslint/blob/master/Makefile.js#L570-L575

**Comment by TheAlphaNerd** [comment]
@mhdawson I added the error I got from the ppcbe machine

**Comment by mhdawson** [comment]
Sounds like the both relate to phantomjs support for ppc platforms so thats what we should follow up on .

**Comment by TheAlphaNerd** [comment]
I want to make a note in here that I have temporarily turned off PPC until we can fix the failures. @mhdawson we can spin up a different CI configuration specifically for PPC if you want to run some tests independently

**Comment by TheAlphaNerd** [comment]
This is fixed and in production!
