### ISSUE TITLE
can we skip debian8-x86

### ISSUE THREAD

**Issue by refack** [nodejs/citgm#575]
The test CI cluster has only one debian8-x86 worker. While a "regular" `node-test-commit` takes less than 15 minutes, a CITGM run takes a little bit more than an hour, so it becomes a CI bottleneck.

The K.I.S.S. solution is not to run CITGM on that platform so I'm asking ;)

FYI:
1. Node 9 and 10 have degraded linux x86 to experimental
3. We have 3 debian8-__x64__ so that is not a problem

**Comment by richardlau** [comment]
This was [done](https://github.com/nodejs/citgm/pull/751#issuecomment-537726053). We still test on debian9-x64.
