### ISSUE TITLE
Add Richard Lau to citgm-admins list

### ISSUE THREAD

**Issue by richardlau** [nodejs/citgm#622]
I'm volunteering to look into https://github.com/nodejs/build/issues/1577 and any other citgm related job issue(s). Being added to the citgm-admins list would allow me to configure the jobs in the CI.

Based on the criteria in https://github.com/nodejs/build/blob/master/doc/process/jenkins_job_configuration_access.md: 
* Does the scope and size of the need justify providing access.
  * I am a member of nodejs/citgm and am volunteering to maintain/fix citgm jobs such as https://github.com/nodejs/build/issues/1577.
* Is the individual a Node.js collaborator? If so then access should be allowed provided the first point is satisfied.
  * Yes, I am a Node.js core collaborator.
* Length and consistency of involvement with Node.js working groups and/or community.
  * Been active in community since 2015 and joined was added to nodejs/citgm in [March 2017](https://github.com/nodejs/citgm/issues/381).
* Consequences to the individual in case of mis-behaviour. For example, would they potentially lose their job if they were reported as mis-behaving to their employer? Would being banned from involvement in the Node.js community negatively affect them personally in some other way?
  * I work for IBM in a job tied to working in the Node.js community so being banned would definitely negatively affect me.
* Are there collaborators who work with the individual and can vouch for them.
  * Maybe @gdams and/or @mhdawson?

cc @nodejs/citgm-admins

**Comment by MylesBorins** [comment]
+1 if there are no objections in the next 24 hours I'll move forward with this. As the next two days are national holidays please feel free to ping me on irc to remind me to do this

**Comment by targos** [comment]
+1

**Comment by gdams** [comment]
+1

**Comment by MylesBorins** [comment]
I've gone ahead and landed as I plan to be AFK most of tomorrow (let's see how successful I am at that)
