### ISSUE TITLE
Tracking issue to make tests pass on Windows

### ISSUE THREAD

**Issue by targos** [nodejs/citgm#642]
/cc @bzoz 

https://github.com/nodejs/citgm/pull/641 fixes 10 tests.

**Comment by targos** [comment]
Issue with `test/npm/test-npm-test.js` and `test/yarn/test-yarn-test.js` is that the `fake-node` executable is not compatible with Windows. I'm working on a fix.

**Comment by richardlau** [comment]
Probably way outdated, but there is https://github.com/nodejs/citgm/issues/276

**Comment by targos** [comment]
I have almost everything fixed locally

**Comment by targos** [comment]
https://github.com/nodejs/citgm/pull/645 fixes the remaining issues
