### ISSUE TITLE
Execution of local bin scripts fails on Windows

### ISSUE THREAD

**Issue by targos** [nodejs/citgm#652]
To reproduce:

```
citgm bufferutil
```

It cannot find `node-gyp-build`. Probably another PATH issue...

**Comment by targos** [comment]
@bzoz any idea? I'm pretty sure `process.env.PATH` contains the correct `node_modules/.bin` directory (it's in the npm error log) so I don't know how to debug this further.

**Comment by richardlau** [comment]
is it only `bufferutil` that fails (due to `node-gyp-builld` (which is not the usual `node-gyp` used for native module compilation))?

**Comment by targos** [comment]
I think it's actually more than that. If there is an npm lifecycle script (install, postinstall, prepare) that calls a local dep, it fails.

**Comment by targos** [comment]
I'm going afk now but I will try to create a small module with such a case later to use in our tests

**Comment by targos** [comment]
See: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1688/nodes=win-vs2017/testReport/junit/(root)/citgm/vinyl_v2_2_0/

This really seems to be a general issue, not only during install.

**Comment by targos** [comment]
See https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1688/nodes=win-vs2017/#showFailuresLink for all modules failing because of this

**Comment by targos** [comment]
I made a simple bin script module here: https://github.com/targos/citgm-bin-script
I included it in the dependencies of another one here: https://github.com/targos/omg-i-pass-with-local-bin
This passes on Windows and Linux, so the problem is not with all bin scripts. I'm going to check what is different with `mocha`

**Comment by bzoz** [comment]
`citgm https://github.com/targos/omg-i-pass-with-local-bin/archive/master.tar.gz` fails for me (`'citgm-bin-script' is not recognized as an internal or external command`)

`bufferutil` also fails, but `https://github.com/archiverjs/node-crc32-stream/archive/master.tar.gz` works

**Comment by targos** [comment]
I didn't think this could get even more weird 😆

**Comment by bzoz** [comment]
And now (without changing anything in citgm) both `citgm https://github.com/targos/omg-i-pass-with-local-bin/archive/master.tar.gz ` and `citgm bufferutil` works 🤷‍♂️. Maybe there was a bug in mocha or npm?

**Comment by targos** [comment]
I don't know what to think of it but you're right, everything works now...

**Comment by targos** [comment]
I can reproduce with these:

- `citgm level`
- `citgm q`

**Comment by MylesBorins** [comment]
extensive windows failures in this run --> https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1718/nodes=win-vs2017/testReport/

**Comment by BridgeAR** [comment]
This happens pretty frequently and the citgm output becomes pretty hard to read that way.

@refack PTAL

**Comment by refack** [comment]
Will do, first thing tomorrow.

**Comment by BridgeAR** [comment]
This is still unresolved. I do not have a Windows machine, so I can't look into this.

@refack do you still plan on pursuing this?

**Comment by targos** [comment]
looks like it's not reproducible anymore 🤷‍♂
