### ISSUE TITLE
Error: no-repository-field in package.json 

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/citgm#687]
- **Node Version**: v12.0.0-pre (current master)
- **CitGM Version**: current 
- **Platform**: uncertain

It seems like CITGM currently fails with a weird error:

`Error: no-repository-field in package.json`

https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1762/nodes=ppcle-ubuntu1404/testReport/junit/(root)/citgm/_nearform_doctor_v4_0_1/

There is definitely a repository field in the modules package.json, so I expect the error on CITGM side but I might be wrong. Could be a peer dependency that fails?

**Comment by targos** [comment]
I didn't see this in recent runs. Can we close?
