### ISSUE TITLE
Do more members of the team want npm release permissions?

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#690]
LMK

**Comment by richardlau** [comment]
@MylesBorins If you would like more people to be able to release on npm then I can volunteer (I've done the last few core-validate-commit releases). 

I'm assuming https://github.com/nodejs/citgm/blob/master/RELEASES.md is still accurate (with the possible question over `Any member of the @nodejs/citgm team can make a release.`).

Also do you know what version 4 of CITGM on https://www.npmjs.com/package/citgm is based on as I only see 3.4.8 in this repository?

**Comment by targos** [comment]
npm references `ffd890144052547240c1e1b9a9d5a663dd068e55` as the git HEAD for this release. It is not in GitHub so I guess @MylesBorins forgot to push something?

**Comment by MylesBorins** [comment]
oh gosh... it looks like I made a release and didn't push the commit... I've gone ahead and pushed the tag... but we are now missing that specific commit in master. Sincere apologies

**Comment by richardlau** [comment]
@MylesBorins Thanks for fixing the 4.0.0 issue. My offer to help out with citgm releases still stands if you're happy for me to have npm release permissions.

**Comment by MylesBorins** [comment]
@richardlau done!

**Comment by richardlau** [comment]
FYI Did a 4.0.1 release. Shout if I've missed anything.

**Comment by BridgeAR** [comment]
@MylesBorins I guess it might indeed be good to also get the permission. Thanks.

**Comment by MylesBorins** [comment]
Done

**Comment by targos** [comment]
I believe this can be closed.
