### ISSUE TITLE
set npm progress = false

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/citgm#71]
https://github.com/npm/npm/issues/11283#issuecomment-175246823

We should see a 20% speed up in npm install using this change.

CI: https://ci.nodejs.org/job/thealphanerd-smoker/56/

**Comment by rvagg** [comment]
fine by me, if it's actually printing the progress bar while in citgm, doesn't make sense to add more output noise anyway although I think Rebecca fixed the significant bugs in the progress bar package for the latest version of npm

**Comment by garthk** [comment]
@iarna's fix is in `are-we-there-yet` but the update isn't dragged in on `npm install --global npm` because `bundleDependencies`.

**Comment by garthk** [comment]
Nuts; I mis-read `package.json` in `npmlog` The `npm` 3.7.1 preview is still on `are-we-there-yet`1.0.6.

**Comment by TheAlphaNerd** [comment]
Since we do not log the progress bar anyways I'm going to close this and leave the option enabled
