### ISSUE TITLE
Allow testing subsystems

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#72]
Currently we have a single large lookup table.

If we split the look up into subsystems (as we do our commits) we could use a flag to specify only testing a subset of the packages.

**Comment by jasnell** [comment]
+1 ... this would be especially helpful for streams.

**Comment by bengl** [comment]
Would a `tag` field in lookup.json be good for this? This is useful for my purposes as well. Could tag by subsystem, or other completely arbitrary purposes. Then have `--with-tags` and `--exclude-tags` options for `citgm-all`.

**Comment by TheAlphaNerd** [comment]
I think tags are a really great way to do this!

**Comment by MylesBorins** [comment]
@gdams is this something you might be interested in helping to design for a v2.0?

**Comment by gdams** [comment]
@MylesBorins sure i'll take a look this week and see what I can put together
