### ISSUE TITLE
Allow Node.js flags to be passed through

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/citgm#724]
It would actually be great to add an option to pass through Node.js options. That way we could test e.g., `--throw-deprecation` and `--unhandled-rejections=strict`. I can't think of a great way to implement this since CITGM is intended to run as global module besides spawning a child_process (seems hacky but it should work).

We could add a new option like `--node-options=--unhandled-rejections=strict,--throw-deprecation`.

**Comment by richardlau** [comment]
`NODE_OPTIONS`?

@targos How did you run CITGM in https://github.com/nodejs/citgm/issues/605?

**Comment by BridgeAR** [comment]
@richardlau ah, of course. It's a bit late here. It should be possible to just prefix the command with `NODE_OPTIONS=...`. Due to that this request seems obsolete.
