### ISSUE TITLE
jade repo is incorrect in published version

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/citgm#75]
patched in https://github.com/pugjs/jade/pull/2238#event-538367264

waiting for it to be released

**Comment by TheAlphaNerd** [comment]
So it looks like this will never be fixed in jade, we should likely start testing pug instead

**Comment by jasnell** [comment]
+1 .. yeah, jade is pretty much dead at this point.

**Comment by bengl** [comment]
I think this is taken care of by 708574e and 4426601, and so this can be closed?
