### ISSUE TITLE
argument to skip specific module in citgm-all

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#76]
it may be easier to add known failures to the arguments rather than constantly modifying the lookup

**Comment by bengl** [comment]
This could be part of [tagging](https://github.com/nodejs/citgm/issues/72), or at least be filtered in the same spot in the code.

**Comment by gdams** [comment]
Closing as [tagging](https://github.com/nodejs/citgm/issues/72) will be able to cover this
