### ISSUE TITLE
EBUSY test failure on Travis on Windows

### ISSUE THREAD

**Issue by richardlau** [nodejs/citgm#768]
> 
> 
> I tried rebasing for the travis Windows CI fix, seems all versions but 8 passed

For posterity the failure:
https://travis-ci.com/nodejs/citgm/jobs/251735785#L809-L822
```console
    # Subtest: grab-project: teardown

        not ok 1 - EBUSY: resource busy or locked, rmdir 'C:\Users\travis\AppData\Local\Temp\citgm-1572592898249'

          ---

          errno: -4082

          code: EBUSY

          syscall: rmdir

          path: C:\Users\travis\AppData\Local\Temp\citgm-1572592898249

          tapCaught: returnedPromiseRejection

          test: "grab-project: teardown"

          ...

        

        1..1

        # failed 1 test

    not ok 10 - grab-project: teardown # time=691.313ms
```
I thought `rimraf` was supposed to handle `EBUSY` on Windows?

_Originally posted by @richardlau in https://github.com/nodejs/citgm/pull/728#issuecomment-548705211_

Appears to be flaky (doesn't occur every time).

**Comment by BridgeAR** [comment]
It might be a good idea to use the Node.js own fs.rmdir recursive option? That would hopefully fix this.

**Comment by MylesBorins** [comment]
Recursive rmdir is not supported on 10.x so CITGM won't be able to support native recursive delete until it is EOL

**Comment by BethGriggs** [comment]
Closing as we've moved off Travis.
