### ISSUE TITLE
CITGM Jenkins jobs by release line

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/citgm#771]
Apologies if this has been raised before... 

Could it be useful to have separate CITGM Jenkins job for each supported release line (and one for master)? I think that way we could make better use of the "Latest Test Result" feature - and it may make it easier to see the CITGM results trend for the specific release line. 

![Screenshot 2019-11-21 at 11 48 19](https://user-images.githubusercontent.com/8297234/69335453-e8c17480-0c54-11ea-897c-b338ee04dc29.png)

I think we could lower the number of historic builds stored per job to reduce the storage/space impact. 

//cc @BridgeAR as I think you suggested this offline
//cc @nodejs/citgm thoughts?

**Comment by BethGriggs** [comment]
Does anyone have any thoughts on this? -  Maybe ping @nodejs/build?

**Comment by richardlau** [comment]
Would it just be releasers running the release line jobs? (And for regular PR’s collaborators would run the one for master?)

With a build hat one issue is quadrupling the maintenance burden of keeping the jobs running (e.g. when infrastructure needs to be updated).

**Comment by BethGriggs** [comment]
I'd _hope_ it'd be possible to do something like what the `daily` jobs do - where the job configuration is defined just once (but with predefined parameters) but we get distinct runs to compare. I don't think that shouldn't introduce too much of a maintenance burden? 

https://ci.nodejs.org/view/Node.js%20Daily/job/node-daily-v10.x-staging/configure 

I can also volunteer to set this up or work with someone on @nodejs/build to do so if Jenkins access will be a problem.

**Comment by rvagg** [comment]
yeah, those lightweight parent jobs that just seed parameters to subjobs probably isn't that big a deal; the sprawling number of jobs is pretty hard to keep track and we end up with a lot of cruft, but I don't think that's been a massive burden so far -- at least we seem to be finding ways to trim when we see bloat (and compared to the other burdens we have!)

**Comment by sam-github** [comment]
I'm not sure if this is ideal. I was poking around in citgm, wouldn't it be better to update the lookup.json in citgm so that flakiness is defined per release line?

I think the syntax of the flaky and skip keys is shared, so taking https://github.com/nodejs/citgm/blob/37d0b2fd796a7dfd355d397dd7ee844c8076edda/lib/lookup.json#L186-L187 as an example, it should be possible to put release line specific flakiness expectations in.

Getting the trends working at the price of duplicating the jobs might not be high enough value to overweigh the maintenance cost.

I'm not opposed by any means, but maybe there is a more direct way of addressing whatever the underlying problem is?

**Comment by BethGriggs** [comment]
Keeping flakiness up-to-date on LTS release lines isn't easy to keep up with. Where there is only ~1 release per month for LTS, we do not catch the new flakes or test failures in modules as they appear. (side note: https://github.com/nodejs/citgm/issues/407 was originally suggested in relation to this problem, but I don't think that is being actively pursued.)

  One approach I (we?) take is to kick off two CITGM runs, `v12.x` and the `v12.x.x-proposal`, and then compare the test results to answer the question "Has the proposed release caused any breakages?".  With the 1 month between LTS releases, the previous LTS runs of `citgm-smoker` can be lost as we only store `x` historic builds. Having a separate job would mean we don't lose that history and get the added benefit of the +- failures view.

  I was hopeful that the job could be set up to just call `citgm-smoker` in the same way the daily staging jobs call `node-test-commit` so that there was minimal (but not 0) build overhead. But at the moment we're having issues propagating the test results back up to the parent job - https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-v12.x/13/aggregatedTestReport/

**Comment by BethGriggs** [comment]
> as an example, it should be possible to put release line specific flakiness expectations in.

Is it possible for me to mark a specific module as flaky for just one platform on a release line? For example, mark a module as flaky on AIX on v12.x only.

**Comment by richardlau** [comment]
> 
> 
> > as an example, it should be possible to put release line specific flakiness expectations in.
> 
> Is it possible for me to mark a specific module as flaky for just one platform on a release line? For example, mark a module as flaky on AIX on v12.x only.

I don't think that's possible currently as `lib/match-conditions.js` currently doesn't handle compound conditions (e.g. `12&&aix`).

**Comment by AshCripps** [comment]
We have two new jobs cloned from the main CITGM smoker - https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-v10.x/ and https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-v12.x/.

This is the current solution as having another parent job on top of `citgm-smoker` wasnt getting the aggregated test results sent up, as jenkins doesn't aggregating a aggregate and will require fingerprinting turned on for all subjobs and configurations.

**Comment by AshCripps** [comment]
Both jobs appear to be working so I think this can be closed now?
