### ISSUE TITLE
Remove darwin from flaky platform of readable-stream

### ISSUE THREAD

**Issue by danielleadams** [nodejs/citgm#787]
- **Node Version**:
10.19.0, 12.16.1, 13.9.0

- **CitGM Version**:
5.1.5

- **Platform**:
Darwin x86_64

I pulled down readable-stream to my local machine (macOS) to see if any of the flaky tests could be reproduced with the supported versions of Node - wasn't able to catch any flaky tests.

It looks like it's been marked as flaky since before the list was alphabetized 15 months ago (https://github.com/nodejs/citgm/pull/646), so opening this issue to discuss removing `darwin` from flaky platforms for `readable-stream` module here: https://github.com/nodejs/citgm/blob/master/lib/lookup.json#L364.

**Comment by BethGriggs** [comment]
Looks good on Darwin on CI
- v10.x CI: https://ci.nodejs.org/job/citgm-smoker-nobuild/739
- v12.x CI: https://ci.nodejs.org/job/citgm-smoker-nobuild/740
- v13.x CI: https://ci.nodejs.org/job/citgm-smoker-nobuild/741
