### ISSUE TITLE
Node.js v14.x failures

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/citgm#797]
Raising this issue to cover failures and flakes for Node.js 14.

https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2314/testReport/

All platforms
- [x] citgm.resolve-v1.15.1 failing on all platforms - https://github.com/nodejs/node/pull/31553
- [x] uuid-v7.0.3
- [x] eslint-plugin-jest-v23.8.2

Multiple
- [x]  ember-cli-v3.17.0

**Comment by targos** [comment]
`resolve` is expected to fail at the moment.
@ljharb I don't remember what we needed to do to make sure it's fixed by the release of v14 ?

**Comment by ljharb** [comment]
I have to publish a new version, and I have to have an unbreakable commitment that v14.0.0 will be the first version in which `fs/promises` is a builtin module so that I can safely publish a new patch of `resolve` prior to v14 being released.

**Comment by BethGriggs** [comment]
@ljharb, v14.x is due to be released Tuesday 21st April containing https://github.com/nodejs/node/pull/31553 (I don't want to say _unbreakable commitment_, but there are no plans to back this PR out of v14.x.)

**Comment by dominykas** [comment]
We do have https://github.com/nodejs/package-maintenance/issues/261 open in package-maintenance - but a little unsure on what are the steps that need to be taken here? How can I help?

**Comment by ljharb** [comment]
@BethGriggs v1.16.0 of resolve now considers `fs/promises` a core module in node 14+.

**Comment by BethGriggs** [comment]
This issue is fairly stale and I believe each of the failures have been addressed.
