### ISSUE TITLE
Replace "master" attribute in lookup

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#820]
Currently we use "master" in the lookup to imply that we want to fetch the "default branch" of a proejcts GitHub repo. This is a misnomer as projects can utilize a number of different default branch names, this repo for example now uses main.

I'd like to suggest we change the name of that attribute, perhaps to `defaultBranch` or `useGit` or something similarly descriptive and more accurate. I need to review the logic one more time to figure out the best way to do it. One thing we can also do is keep `master` as an alias and print a deprecation message, removing it in a Major version of CITGM.

**Comment by ljharb** [comment]
Setting it to `HEAD` should Just Work, i think?

**Comment by MylesBorins** [comment]
@ljharb maybe?

https://github.com/nodejs/citgm/blob/main/lib/lookup.js is where a good chunk of the logic lives in setting up the context but honestly I'd have to do some spelunking to figure out how we are fetching the meta data and the eventual tarball. There is also internal logic that involves cloning the repo. I'm not 100%, but I don't know if HEAD will just work out of the box for all the places we utilize this info

**Comment by ljharb** [comment]
Anywhere that supports a git "versionish" should; certainly manually switching to "main" would work anywhere else.

**Comment by targos** [comment]
I opened https://github.com/nodejs/citgm/pull/848 to fix this.
