### ISSUE TITLE
eslint-plugin-jest v24.0.0 broken on CI

### ISSUE THREAD

**Issue by richardlau** [nodejs/citgm#824]
- **Node Version**: 14.9.0
- **CitGM Version**: 7.1.4
- **Platform**: multiple

Looks like the most recent version of `eslint-plugin-jest`, v24.0.0, is broken when running in CITGM on our CI:
e.g. https://ci.nodejs.org/job/citgm-smoker/2458/nodes=ubuntu1804-64/testReport/junit/(root)/citgm/eslint_plugin_jest_v24_0_0/
```
undefinedUsage Error: Unrecognized or legacy configuration settings found: ignoreEngines - run "yarn config -v" to see the list of settings supported in Yarn (in <environment>)
 $ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds]
```

I can reproduce locally with eslint-plugin-jest@v24.0.0 but not with eslint-plugin-jest@v23.20.0 (the previous release).

```
bash-4.2$ node bin/citgm eslint-plugin-jest
info:    starting            | eslint-plugin-jest  
info:    lookup              | eslint-plugin-jest  
info:    lookup-found        | eslint-plugin-jest  
info:    eslint-plugin-jest lookup-replace| https://github.com/jest-community/eslint-plugin-jest/archive/1392cf39d8d8fcc5d9bbcc92e3388ac
info:    eslint-plugin-jest npm:| Downloading project: https://github.com/jest-community/eslint-plugin-jest/archive/1392cf39d8d8fcc5d9bb
info:    eslint-plugin-jest npm:| Project downloaded eslint-plugin-jest-24.0.0.tgz
info:    eslint-plugin-jest yarn:| yarn install started
error:   failure             | Install Failed      
error:   failing module(s)   |                     
error:   module name:        | eslint-plugin-jest  
error:   version:            | 24.0.0              
error:   error:              | Install Failed      
error:   error:              | undefinedUsage Error: Unrecognized or legacy configuration settings found: ignoreEngines - run "y
error:                       |                                                                                                          
error:                       | $ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds]              
error:   done                | The smoke test has failed.
info:    duration            | test duration: 4732ms
bash-4.2$ 
```

cc @SimenB

**Comment by SimenB** [comment]
Ah sorry, we migrated to yarn v2. Removing `--ignore-engines` should be enough (they've removed the flag and just warn now)

**Comment by richardlau** [comment]
We set `YARN_IGNORE_ENGINES` unilaterally since https://github.com/nodejs/citgm/pull/738 for https://github.com/nodejs/citgm/issues/737. We can take it out but we'll need to check doing so doesn't affect other modules which use `yarn`.

**Comment by SimenB** [comment]
Hmm. We can run `yarn --version` - if v2 do not add the arg?

**Comment by arcanis** [comment]
If checking the version is possible that would be the easiest workaround. The second best one (but still significantly less good) would be to modify `yarnPath` to refer to a wrapper script that would remove the extraneous configuration keys 🤔

**Comment by richardlau** [comment]
> 
> 
> Hmm. We can run `yarn --version` - if v2 do not add the arg?

https://github.com/nodejs/citgm/pull/831 does this.

It also looks like `eslint-plugin-jest` fails on big endian platforms (e.g. AIX, LinuxONE) and should be skipped on those (we already skip on AIX):
https://ci.nodejs.org/job/citgm-smoker/nodes=rhel7-s390x/2473/testReport/(root)/citgm/eslint_plugin_jest_v24_0_2/
```
undefinedType Error: Cannot create property 'message' on string 'Runtime error: expected the system to be little-endian!'
     at Module.w (/data/iojs/tmp/citgm_tmp/1984e210-f804-40a3-ab37-a5b90c16f8f1/eslint-plugin-jest/.yarn/releases/yarn-sources.cjs:2:372125)
     at o (/data/iojs/tmp/citgm_tmp/1984e210-f804-40a3-ab37-a5b90c16f8f1/eslint-plugin-jest/.yarn/releases/yarn-sources.cjs:2:268762)
     at Function.find (/data/iojs/tmp/citgm_tmp/1984e210-f804-40a3-ab37-a5b90c16f8f1/eslint-plugin-jest/.yarn/releases/yarn-sources.cjs:2:269118)
     at async /data/iojs/tmp/citgm_tmp/1984e210-f804-40a3-ab37-a5b90c16f8f1/eslint-plugin-jest/.yarn/releases/yarn-sources.cjs:2:247308
     at async r (/data/iojs/tmp/citgm_tmp/1984e210-f804-40a3-ab37-a5b90c16f8f1/eslint-plugin-jest/.yarn/releases/yarn-sources.cjs:2:247002)
```

**Comment by SimenB** [comment]
> #831 does this.

🎉 

> It also looks like `eslint-plugin-jest` fails on big endian platforms

Wat. I've never seen that error and have no idea where it comes from. I tried grepping in the repo (which has both the yarn script and `node_modules`) without finding that string

**Comment by arcanis** [comment]
It seems like Emscripten [doesn't support big endian systems](https://emscripten.org/docs/porting/guidelines/portability_guidelines.html#code-that-cannot-be-compiled), and we use it for the zip support 🤔

> Emscripten-compiled code currently requires a little-endian host to run on, which accounts for 99% of machines connected to the internet. This is because JavaScript typed arrays (used for views on memory) obey the host byte ordering and LLVM needs to know which endianness to target.
