### ISSUE TITLE
Node.js 16 failures

### ISSUE THREAD

**Issue by targos** [nodejs/citgm#852]
I started a run (with citgm's main branch) against Node.js master to check the current status: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2643/

**Comment by targos** [comment]
New run: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2650/

@devinivy It looks like `hapi` is going to have issues: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2650/nodes=fedora-last-latest-x64/testReport/junit/(root)/citgm/_hapi_hapi_v20_1_1/

@richardlau `node-report` seems a bit too strict in its tests for version numbers: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2650/nodes=fedora-last-latest-x64/testReport/junit/(root)/citgm/node_report_v2_2_11/

@nodejs/npm: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2650/nodes=fedora-last-latest-x64/testReport/junit/(root)/citgm/npm_v7_6_3/

@alexlamsl `uglify-js` is failing because of a spec change: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2650/nodes=fedora-last-latest-x64/testReport/junit/(root)/citgm/uglify_js_v3_13_1/
See https://github.com/tc39/ecma262/pull/2256

**Comment by devinivy** [comment]
We published hapi 20.1.2, and it should contain fixes for those issues 👍

**Comment by richardlau** [comment]
> New run: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2650/
>  
> @richardlau `node-report` seems a bit too strict in its tests for version numbers: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2650/nodes=fedora-last-latest-x64/testReport/junit/(root)/citgm/node_report_v2_2_11/
> 

`node-report` is comparing the versions of Node.js dependencies in the report to `process.versions` -- the failure is occurring since  we use each value in `process.versions` to construct a regular expression and the version string for OpenSSL for the fork we're now using contains a `+` character which needs to be escaped for use in a regular expression. Raised https://github.com/nodejs/node-report/pull/147 to fix.

**Comment by MylesBorins** [comment]
@targos the `npm` failure seems to be related to the pre-release version of Node.js causing weird issues with the `npm install` phase.

**Comment by BethGriggs** [comment]
CITGM isn't particularly healthy on the v16.0.0 proposal (132 failures). v16.0.0 has not diverged from master yet (just slightly behind), so I suspect runs on master yield similar results.

Run on rc.3 (3bc20dc) - https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2671/testReport/

Probably best to start by capturing the failures that are occurring on many platforms:

- [ ] @hapi/hapi-v20.1.2
  - Error: `The following leaks were detected:atob, btoa, performance`
- [ ] @hapi/shot-v5.0.5
  - Error: `The following leaks were detected:atob, btoa, performance`
- [ ] nan-v2.14.2
  -  [Link](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2671/nodes=debian9-64/testReport/(root)/citgm/nan_v2_14_2/)
- [x] node-report-v2.2.11
  - Now skipped, but waiting on CITGM publish.
- [ ] npm-v7.8.0
  - Error: `Error: Cannot find module './reports/base'`
- [ ] socket.io-v4.0.1
  - ` socket.io socket should not fire events more than once after manually reconnecting:`
- [ ] uglify-js-v3.13.3 
  - [Link](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2671/nodes=debian9-64/testReport/(root)/citgm/uglify_js_v3_13_3/)
- [ ] undici-v3.3.3
  - [Link](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2671/nodes=debian9-64/testReport/(root)/citgm/undici_v3_3_3/)
- [ ] yargs-v16.2.0
  - [Link](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2671/nodes=debian9-64/testReport/(root)/citgm/yargs_v16_2_0/)
- [ ] yeoman-generator-v5.2.0'
  - [Link](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2671/nodes=debian9-64/testReport/(root)/citgm/yeoman_generator_v5_2_0/)

**Comment by richardlau** [comment]
>     * [ ]  undici-v3.3.3
>       
>       * [Link](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2671/nodes=debian9-64/testReport/(root)/citgm/undici_v3_3_3/)
> 

At least one of the failures,
```
     # Subtest: 20 times GET with pipelining 10
         1..61
         not ok 1 - (unnamed test)
           ---
           code: DEP0111
           ...
```
 Is the [`process.binding` deprecation](https://github.com/nodejs/node/blob/master/doc/api/deprecations.md#dep0111-processbinding) which was removed from undici in https://github.com/nodejs/undici/pull/564 but hasn't been released. 
Refs: https://github.com/nodejs/node/pull/37813#issuecomment-804317565.

**Comment by BethGriggs** [comment]
I can reproduce the npm-v7.8.0 failures locally on the `v16.0.0-proposal` build 🤔 

```
➜  cli git:(latest) ✗ ~/node/out/Release/node --version
v16.0.0
➜  cli git:(latest) ✗ ~/node/out/Release/node ~/cli/node_modules/tap/bin/run.js
Error: Cannot find module './reports/base'
Require stack:
- /Users/bgriggs/cli/node_modules/jackspeak/noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at resolveFileName (/Users/bgriggs/cli/node_modules/tap/node_modules/resolve-from/index.js:17:39)
    at resolveFrom (/Users/bgriggs/cli/node_modules/tap/node_modules/resolve-from/index.js:31:9)
    at module.exports (/Users/bgriggs/cli/node_modules/tap/node_modules/resolve-from/index.js:34:41)
    at importJSX (/Users/bgriggs/cli/node_modules/tap/node_modules/import-jsx/index.js:24:21)
    at module.exports (/Users/bgriggs/cli/node_modules/tap/node_modules/treport/lib/index.js:13:18)
    at exports.makeReporter (/Users/bgriggs/cli/node_modules/tap/bin/run.js:422:23)
    at runTests (/Users/bgriggs/cli/node_modules/tap/bin/run.js:744:3)
    at mainAsync (/Users/bgriggs/cli/node_modules/tap/bin/run.js:244:5)
    at main (/Users/bgriggs/cli/node_modules/tap/bin/run.js:127:3) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/bgriggs/cli/node_modules/jackspeak/noop.js' ]
}
```

My `git bisect` is pointing to the V8 9.0 upgrade https://github.com/nodejs/node/pull/37587 - as the last known good commit to build/pass npm test appears to be the previous commit, `802b3e7cf9`. But I haven't yet convinced myself that #37587 is responsible (or why).

/cc @nodejs/npm

**Comment by ruyadorno** [comment]
hi @BethGriggs! That is looking more like a https://github.com/tapjs/node-tap (which is the test framework we're using) problem than a npm one, we'll dig into it!

**Comment by BethGriggs** [comment]
Thanks @ruyadorno. From further digging around tap I found https://github.com/tapjs/node-tap/issues/624 - which shows a similar/relevant error. As suggested there, passing `--reporter classic` does run through the test suite and the npm suite passes. So I suspect this issue would impact more than just npm's test suite.

**Comment by BethGriggs** [comment]
Results from the v16.0.0-rc.5 - i've omitted ones that are only on one platform and familiar timeout flakes.

- [ ] citgm.@hapi/hapi-v20.1.2
  -  The following leaks were detected:atob, btoa, performance - https://github.com/hapijs/lab/issues/1003
- [ ] citgm.@hapi/shot-v5.0.5
  -  The following leaks were detected:atob, btoa, performance - https://github.com/hapijs/lab/issues/1003
- [ ] citgm.body-parser-v1.19.0
  -  http methods should support PRI requests - refs https://github.com/nodejs/llhttp/pull/103#issuecomment-823114289
- [ ] citgm.express-v4.17.1
  -  http methods should support PRI requests - refs https://github.com/nodejs/llhttp/pull/103#issuecomment-823114289
- [ ] citgm.fastify-v3.14.2
  - Various - including 'not ok 7 - test/close-pipelining.test.js'
- [ ] citgm.jest-v26.6.3
  - Received message: [31m"exports.createRequireFromPath is not a function"
- [ ] citgm.nan-v2.14.2
  - [Link](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2671/nodes=debian9-64/testReport/(root)/citgm/nan_v2_14_2/) - https://github.com/nodejs/nan/pull/910
- [ ] citgm.npm-v7.10.0
  - Error: Cannot find module './reports/base' - refs: https://github.com/nodejs/citgm/issues/852#issuecomment-816317278
- [ ] citgm.pump-v3.0.0
  -  Error: timeout
- [ ] citgm.resolve-v1.20.0 [Windows Only]
  -  throw 'sync: no match';
- [ ] citgm.router-v1.3.5
  - should respond to a PRI request - refs https://github.com/nodejs/llhttp/pull/103#issuecomment-823114289
- [ ] citgm.socket.io-v4.0.1
  - Segfault on IBM platforms
- [ ] citgm.torrent-stream-v1.2.1
  - SIGTERM
- [ ] citgm.uglify-js-v3.13.4
  - [Link](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2671/nodes=debian9-64/testReport/(root)/citgm/uglify_js_v3_13_3/) - refs: https://github.com/mishoo/UglifyJS/issues/4846
- [ ] citgm.underscore-v1.13.1
  - npm ERR! 404 Not Found - GET 
- [ ] citgm.yargs-v16.2.0
  -  (!) Unresolved dependencies
- [ ] citgm.yeoman-generator-v5.2.0
  - [Link](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2679/nodes=ubuntu1804-64/testReport/(root)/citgm/yeoman_generator_v5_2_0/)

**Comment by targos** [comment]
>  citgm.jest-v26.6.3
> Received message: [31m"exports.createRequireFromPath is not a function"

@SimenB

**Comment by SimenB** [comment]
Thanks for the heads up! From https://github.com/nodejs/node/pull/37201 I assume - will tweak our tests (we have some feature detection so it's a fallback if `createRequire` isn't there, seems we've messed that up).

**Comment by BethGriggs** [comment]
> citgm.fastify-v3.14.2
> Various - including 'not ok 7 - test/close-pipelining.test.js'

@mcollina just FYI  in case this isn't on your radar yet, fastify is failing on `master`/`v16.0.0-rc.5` - [link to CITGM error](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2679/nodes=ubuntu1804-64/testReport/(root)/citgm/fastify_v3_14_2/)

**Comment by ljharb** [comment]
Can you link to the failure for resolve, so i can look into it?

**Comment by targos** [comment]
@ljharb https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2671/nodes=win-vs2019/testReport/junit/(root)/citgm/resolve_v1_20_0/

**Comment by mcollina** [comment]
https://github.com/nodejs/undici/pull/754 fixes the problem for Fastify.

**Comment by ljharb** [comment]
@targos thanks! has anything changed with symlinks in node 16 that i could investigate? I don't have a windows machine to test on.

**Comment by BethGriggs** [comment]
@ljharb I skimmed back a few CITGM builds and noticed the resolve failure was also present on runs for [v15.13.0](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/nodes=win-vs2019/2660/testReport/(root)/citgm/resolve_v1_20_0/) and [v14.16.1](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/nodes=win-vs2019/2662/testReport/(root)/citgm/resolve_v1_20_0/). I'm not sure how far back the failure goes, but I'm thinking that it's possibly related to our CITGM set up.

Would any one with a Windows box mind confirming if resolve's tests pass locally (both directly and through CITGM)?

**Comment by targos** [comment]
It's possible that the Windows machines in CI are not configured in development mode. This is mandatory to be able to create symlinks from a non-administrator account.

**Comment by ljharb** [comment]
Thanks, hopefully that’s the case :-)

(Some tooling that’d be nice is auto-filing an issue when something fails a few times in a row, and tagging the maintainers of that package)

**Comment by ljharb** [comment]
@targos Are the resolve failures on windows … resolved?

**Comment by targos** [comment]
@ljharb no, `resolve` still fails on Windows

**Comment by ljharb** [comment]
Is there an open issue to track that, since it seems to be CITGM-specific?

**Comment by targos** [comment]
I don't think so. It should be a `nodejs/build` issue about enabling symlinks on Windows machines
