### ISSUE TITLE
Noisy errors hides real errors when testing `jest`

### ISSUE THREAD

**Issue by SimenB** [nodejs/citgm#875]
- **Node Version**: N/A
- **CitGM Version**: N/A
- **Platform**: N/A

Ref https://github.com/nodejs/node/issues/40030#issuecomment-915049916, it seems #868 is not enough. @targos could you expand a bit on what's wrong? I would have thought removing the examples would also remove mongo, but apparently not?

**Comment by targos** [comment]
Here's an example: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2754/nodes=fedora-latest-x64/testReport/junit/(root)/citgm/jest_v27_1_0/

**Comment by targos** [comment]
I just realized that there is no citgm release that includes https://github.com/nodejs/citgm/pull/868 🤦🏻

**Comment by targos** [comment]
I just published version 8.0.2. This should be fixed.

**Comment by SimenB** [comment]
Ah, wonderful 👏
