### ISSUE TITLE
CI fails on Windows and Node.js >=14.x

### ISSUE THREAD

**Issue by targos** [nodejs/citgm#879]
See for example https://github.com/nodejs/citgm/runs/3996727979?check_suite_focus=true

We started to see the failure with commit https://github.com/nodejs/citgm/commit/b73cb0f07188307e0745e09b361c64610f37c5f8, which only increments the version number, so the failure is due to something external, like a change in Node.js itself or in a dependency.

**Comment by Trott** [comment]
@nodejs/platform-windows
