### ISSUE TITLE
CITGM status - v17

### ISSUE THREAD

**Issue by targos** [nodejs/citgm#885]
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/1121/

**Comment by targos** [comment]
@mcollina @delvedor I'm not sure why fastify still fails: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/1121/nodes=ubuntu1804-64/testReport/junit/(root)/citgm/fastify_v3_24_1/

It says "# failed 5 of 96 tests" but I see no test with a "not ok" output.

There's also this at the end of the logs:

```
 FakeTimers: clearTimeout was invoked to clear a native timer instead of one created by this library.
 To automatically clean-up native timers, use `shouldClearNativeTimers`.
 (node:5020) [FSTDEP009] FastifyDeprecation: You are using a custom route versioning strategy via the server { versioning: "..." } option, use { constraints: { version: "..." } } option instead.
 (Use `node --trace-warnings ...` to show where the warning was created)
 ERROR: Coverage for lines (99.94%) does not meet global threshold (100%)
 ERROR: Coverage for functions (99.67%) does not meet global threshold (100%)
 ERROR: Coverage for statements (99.94%) does not meet global threshold (100%)
```

**Comment by mcollina** [comment]
The node v17 fixes are not released yet. They will be in the next release (or sooner if @delvedor beat me to it)

**Comment by BethGriggs** [comment]
@targos should we close this as the test run linked is no longer accessible? (I'm hoping #894 will pick up some of the general flakes/platform issues that apply across multiple versions.)
