### ISSUE TITLE
Adding nodejs/releasers as maintainers

### ISSUE THREAD

**Issue by richardlau** [nodejs/citgm#903]
Refs: https://github.com/nodejs/Release/issues/557
Refs: https://github.com/nodejs/citgm/pull/901#issuecomment-1118513519

Any objections to adding the release team (@nodejs/releasers) as maintainers of https://github.com/nodejs/cigtm?

**Comment by Trott** [comment]
Do it!

**Comment by richardlau** [comment]
I've added @nodejs/releasers as maintainers of https://github.com/nodejs/cigtm.
