### ISSUE TITLE
Utilize es6 features

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/citgm#91]
Currently we are not using a number of es6 features that could help streamline the code base.

#86 introduced the use of template strings, which I cannot really live without at this point. I'd love to go through and refactor the code base to use more es6, specifically 

  * let / const
  * arrow functions
  * template strings

I'm open to using other features too, but those are the particular features I've been taking advantage of

**Comment by TheAlphaNerd** [comment]
it is worth mentioning that originally this repo was written in es5 with the intention that it could be used in older versions of node (v0.10 / v0.12).

AFAIK the smoker has not been used once on either of these releases.

**Comment by rvagg** [comment]
oh, I was hoping to start using it on 0.10 and 0.12 once this became more stable, i.e. nowish

can this wait till later in the year as 0.10 and 0.12?

**Comment by TheAlphaNerd** [comment]
absolutely. I'll go through and get rid of es6 :smile:

**Comment by TheAlphaNerd** [comment]
closing this for now... moving discussion regarding cross version support to a new issue
