### ISSUE TITLE
Nobuild jobs will fail on Node.js 18 ubuntu1804-64 

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/citgm#917]
Running CITGM nobuild jobs for Node.js 18 on `ubuntu1804-64` will lead to the following error. I believe this is due to the mismatch in minimum GLIBC requirements from our prebuilt binaries versus the test machines.

```
14:52:44 node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
```

CITGM smoker is unaffected as it is building and testing on the same machine.

**Comment by targos** [comment]
Related: https://github.com/nodejs/build/issues/2931

**Comment by BethGriggs** [comment]
I think this is no longer a pertinent issue as when running `citgm-smoker-nobuild`  for Node.js 18, the job no longer attempts to run on `ubuntu1804-64` (now `rhel8-x64`):

```console
02:03:53 Triggering citgm-smoker-nobuild » aix72-ppc64
02:03:53 Triggering citgm-smoker-nobuild » fedora-last-latest-x64
02:03:53 Triggering citgm-smoker-nobuild » rhel8-x64
02:03:53 Triggering citgm-smoker-nobuild » rhel8-ppc64le
02:03:53 Triggering citgm-smoker-nobuild » debian10-x64
02:03:53 Triggering citgm-smoker-nobuild » win2022-vs2019
02:03:53 Triggering citgm-smoker-nobuild » fedora-latest-x64
02:03:53 Triggering citgm-smoker-nobuild » osx11-x64
02:03:53 Triggering citgm-smoker-nobuild » osx11
02:03:53 Triggering citgm-smoker-nobuild » rhel8-s390x
```

Refs: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/1560/console
