### ISSUE TITLE
Lookup table usage(s)

### ISSUE THREAD

**Issue by gibm** [nodejs/citgm#92]
I am slightly confused by the lookup table. In the README you say that the lookup table basically provides default options for modules, so if you run `citgm lodash` it will check the lookup table to see what the default should be.

However, as I understand it, if you run citgm-all, it will use the lookup table as a list of modules to test (and if you specify your own lookup.json it will use that), and go through testing each one.

If the lookup table has two uses, it'd be good to document it in the README.

**Comment by TheAlphaNerd** [comment]
@gibm this is documented in https://github.com/nodejs/citgm#citgm-all

Please let me know if you think it can be better documented somewhere else

**Comment by gibm** [comment]
Oh yes, fair enough. I was looking at the examples at the end of the Notes section and getting confused by that. 

I was thinking that it might be useful to also document the fields in the lookup.json file, but that would probably clutter the README, and it should be straightforward to work them out from the default one in lib.

**Comment by TheAlphaNerd** [comment]
SGTM. If you have modules that we are not testing that you think we should be please feel free to send a PR.

Closing this issue for now, feel free to keep the convo going

**Comment by gibm** [comment]
It wasn't so much the modules themselves, you seem to test a good variety :smile:. It's just that citgm-all is a really neat way to test multiple modules quickly, so it's often useful to use a custom `lookup.json`. As for the fields, I guess it's pretty straightforward:

 * `"replace": true`  - Get the module from the github repo in the module's package.json, not from npmjs.com (often used when the npm package doesn't include the tests directory)
 * `"master": true`   - Use the master branch
 *  `"prefix": "v"`      - Add the citgm "-v" flag
 *  `"flaky": true`      - Ignore failures
 * `"repo": "https://github.com/pugjs/jade"`   - Use a different github repo

Are there any other things that can be set?

**Comment by TheAlphaNerd** [comment]
prefix is actually used to specify the prefix used in the version itself 8.0 / v8.0 / V8.0

`skip: completely skip the module in a citgm-all run`

and soon to come
`stripAnsi: sanitize and remove ansi data of output`

**Comment by TheAlphaNerd** [comment]
This is a good idea to document. Would you like to take a stab and send a PR?

**Comment by gibm** [comment]
Absolutely, but where would you put it? In the main README.md? In another markdown doc in lib? Or as comments in the lookup.json file itself.

**Comment by TheAlphaNerd** [comment]
I think a section in the readme would make the most sense

**Comment by gibm** [comment]
Ok, will do
