### ISSUE TITLE
Review team access to this repository 

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/citgm#945]
From https://github.com/nodejs/citgm/pull/944#issuecomment-1470748308: 
> @nodejs/releasers has "Maintain" access, and @nodejs/bots has "Write" access. @nodejs/tsc also has "Write" access, but that should probably be revoked, the TSC doesn't ned any special permissions for this repo AFAICT. Neither @nodejs/citgm nor @nodejs/citgm-admins have any rights on this repo, it's probably a mistake 🤷‍♂️

I think we should review and update team access.

My suggestion would be:
 * Write access for `nodejs/citgm*`, `nodejs/releasers`, and `nodejs/bots`
 * Remove explicitly granted access for `nodejs/tsc`
   * This seems unnecessary as they're organisation owners.
   
(I believe the above is in line with @aduh95's comment.)

**Comment by richardlau** [comment]
SGTM

**Comment by aduh95** [comment]
I don’t know if my position matters a lot here as I don’t contribute much to CITGM, but FWIW I usually use « Maintain » rather than « Write » when setting up permissions (e.g. for Corepack, or node-core-test), but the current plan also SGTM.

**Comment by BethGriggs** [comment]
> FWIW I usually use « Maintain » rather than « Write » when setting up permissions (e.g. for Corepack, or node-core-test), but the current plan also SGTM.

Hmm, looking at the access difference, `Maintain` may be more appropriate. Can people 👍🏻 if the agree to the proposal as above, but switching `Write` -> `Maintain`?

**Comment by BethGriggs** [comment]
Updated as proposed.
