### ISSUE TITLE
Proposal - Cleanup the modules failing often

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/citgm#955]
When performing a release, we usually compare the citgm run against the previous CI. This, however, does hide modules that are failing often. Instead of comparing 100 failures with 101 failures and proceeding with the release, we should lower this number the much as we can, otherwise, the citgm will become meanless. 

I think we should:

* When the package fails frequently, ping the module author.
* Drop the package from lookup.json when no response from the "maintainer"

This should help the releasers a lot (plus reducing the citgm time).

cc: @nodejs/releasers

**Comment by targos** [comment]
Isn't it the purpose of the "maintainers" field?

**Comment by RafaelGSS** [comment]
Oh, yeah. My bad. Let me adjust the proposal to cover the second part only.

**Comment by bengl** [comment]
> When the package fails frequently, ping the module author.

If this is going to block releases, it may be worth collecting alternative contact information, since GitHub notifications can be overwhelming (and thus ignored or dealt with in delayed batches) by some folks.

**Comment by RafaelGSS** [comment]
Adding Release-agenda to mention it in the next meeting so we can move it forward

**Comment by joyeecheung** [comment]
Since the CITGM has been red for years, maybe a better approach would be just starting from a clean slate, and gradually add modules back while strictly keeping it green. A red CI in the normally green CI is must noticable, and I feel the approach of trying to remove modules until it's green had not been working well for a long time until this day...

**Comment by RafaelGSS** [comment]
Ref #959

**Comment by targos** [comment]
We discussed this in the WG meeting today. Suggestion is that someone opens a pull request documenting the procedure. Once the PR is accepted and merged, we can close this.

**Comment by RafaelGSS** [comment]
I'm closing it as concluded as the first step has been concluded #958 #929 https://github.com/nodejs/citgm/pull/1035
