### ISSUE TITLE
citgm-fan: test the heads of all major release lines

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#99]
I want to propose a new job that will build the head of each supported release line.

Currently this includes:
- v0.10
- v0.12
- v4.x
- v5.x
- master

This should potentially be a job that is run periodically.

Before starting to go down the path of this I just wanted to check with @nodejs/build to see that they don't mind this kind of stuff running.

**Comment by rvagg** [comment]
Fine by me if it's done off-peak, it'd better be against v0.10-staging, v0.12-staging and v4.x-staging, however. 

Given how little churn there is on the 0.10 and 0.12 branches, perhaps we should do it based on whether there's been a change or not. I'm not sure if Jenkins can handle that easily or not but we use https://github.com/nodejs/build/tree/master/setup/www/tools/nightly-builder to determine this for building nightlies so we don't build again if nothing has changed on a given branch. Perhaps if Jenkins can't do it we just set up a cron job like for nightlies to do it, wouldn't be hard (I think).

**Comment by TheAlphaNerd** [comment]
I think the idea on this fan would have less to do with the churn on the node version, but with churn in the ecosystem itself.

**Comment by joaocgreis** [comment]
Looking at the labels in `thealphanerd-smoker` ([debian8-64](https://ci.nodejs.org/label/debian8-64), [fedora21](https://ci.nodejs.org/label/fedora21), [fedora22](https://ci.nodejs.org/label/fedora22), [fedora23](https://ci.nodejs.org/label/fedora23), [osx1010](https://ci.nodejs.org/label/osx1010), [ppcle-ubuntu1404](https://ci.nodejs.org/label/ppcle-ubuntu1404), [ubuntu1204-64](https://ci.nodejs.org/label/ubuntu1204-64), [ubuntu1404-64](https://ci.nodejs.org/label/ubuntu1404-64), [ubuntu1504-64](https://ci.nodejs.org/label/ubuntu1504-64)), the fedoras and ubuntu1204/1504 only have one machine per label. This means that any test job would have to wait for the smoke test to complete on those platforms. Is it possible to drop/replace them?

Either way, we can do it all on the weekend or have a job for each branch and run one each week day.

**Comment by jbergstroem** [comment]
I can look at adding a bit more redundancy to the test farm, but I think having logic that avoids running citgm too frequently would be very beneficial.

**Comment by mhdawson** [comment]
@rvagg it should be possible to just do it if there have been changes. In IBMs jenkins environment I have something that does that for our v8 beta/stable testing.  Its pretty ugly but does work.

**Comment by MylesBorins** [comment]
Closing for now. @gibfahn feel free to reopen if this is something you would want to explore
